### ISSUE TITLE
UnauthorizedAccessException When Setting Content of ReadOnly RichEditBox

### ISSUE THREAD

**Issue by D4rk-S0ul** [microsoft/microsoft-ui-xaml#10028]
### Describe the bug

Settings the Content of a RichEditBox in CodeBehind works, but only if IsReadOnly="False".
As soon as I make it ReadOnly, I get the follwing exeption:
```ex
System.UnauthorizedAccessException
  HResult=0x80070005
  Message=Attempted to perform an unauthorized operation.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Text.ITextDocumentMethods.SetText(IObjectReference _obj, TextSetOptions options, String value)
   at Microsoft.UI.Text.RichEditTextDocument.SetText(TextSetOptions options, String value)
   at RichEditBoxBug.MainWindow.RichEditBox_Loaded(Object sender, RoutedEventArgs e) in C:\Users\User\Documents\Programming\RichEditBoxBug\RichEditBoxBug\MainWindow.xaml.cs:line 26
   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
   ```

### Steps to reproduce the bug

1. Create a new packaged app
2. Add a RichEditBox
3. Set it's content in CodeBehind using `richEditBox.Document.SetText(TextSetOptions.None, "Hello, World!");`

Alternatively, the [source-code](https://github.com/D4rk-S0ul/RichEditBoxBug) can be found on my GitHub.

### Expected behavior

Even according to the [official documentation](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.richeditbox?view=winrt-26100):
`IsReadOnly` gets or sets a value that indicates whether the **user** can change the text in the [RichEditBox](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.richeditbox?view=winrt-26100).

Therefore, I expect to be able to set the content of a ReadOnly RichEditBox programmatically. The only effect the ReadOnly state should have is preventing UserInput.

### NuGet package version

WinUI 3 - Windows App SDK 1.6.0: 1.6.240829007

### Additional context

**Windows Version**: Windows 11 (23H2): Build 22631.4169
--> Please add this Version to the selectable Windows Versions

**Comment by D4rk-S0ul** [comment]
Is there any further information needed? Just let me know

**Comment by rudyhuyn** [comment]
The current behavior is incorrect and does not align with developer expectations. A developer should not be required to temporarily disable IsReadOnly in order to update the content of a RichEditBox. This introduces unnecessary complexity and creates the possibility that a user may type into the control while it is editable.

This behavior is inconsistent with TextBox, where IsReadOnly allows programmatic updates while still blocking user input. RichEditBox should adopt the same behavior to ensure consistency
