### ISSUE TITLE
Error when running a WinUI Unpackaged app in Visual Studio 2022

### ISSUE THREAD

**Issue by ward-horsfall** [microsoft/microsoft-ui-xaml#10171]
### Describe the bug

Hi,

When I try to run a WInUI app in Visual Studio 2022 Community Version 17.12.0 in "Unpackaged" mode I get the following error:

System.Runtime.InteropServices.COMException
  HResult=0x80040154
  Message=Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.ActivationFactory.Get(String typeName, Guid iid)
   at Microsoft.UI.Xaml.Application.get__objRef_global__Microsoft_UI_Xaml_IApplicationStatics()
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at App4.Program.Main(String[] args) in G:\Data\Users\Ward\Documents\Visual_Studio_Projects\App4\obj\x64\Debug\net8.0-windows10.0.19041.0\win-x64\App.g.i.cs:line 26

This happens if I have it set to either x86 / x64.

The project type I create is: "Blank App, Packaged (WinUI 3 in Desktop)"

Note If I run it as a packaged app it runs without issue.

Thanks
Ward

![Image](https://github.com/user-attachments/assets/caff8d00-001d-4dcb-9c01-cc83cd71425d)

![Image](https://github.com/user-attachments/assets/77381878-6151-4afe-a4d9-e812ed8c353c)

### Steps to reproduce the bug

In Visual Studio 2022 - create a project of type: "Blank App, Packaged (WinUI 3 in Desktop)".

Then set the package type to: (Unpackaged)

### NuGet package version

None

**Comment by castorix** [comment]
There must be, in the Project file :

 	<WindowsPackageType>None</WindowsPackageType>

**Comment by rhenry74** [comment]
same problem here

**Comment by TheSchalck** [comment]
The solution from Castorix have I been looking for the latest week.

When setting the debug setting to Unpackaged, his onliner solved the COMException issue for me

**Comment by vsvsav** [comment]
Until now, for the latest VS 2022, when creating an empty application, this bug, but the solution from https://github.com/castorix helps. Auuu MS, make a new update to the VS.
