### ISSUE TITLE
Rapid Scrolling in TreeView Causes Application Crash in WinUI 3

### ISSUE THREAD

**Issue by datskiy** [microsoft/microsoft-ui-xaml#10248]
### Describe the bug

When scrolling **quickly** through the `TreeView` items in an "up-down-up-down" sequence, the application consistently crashes. This issue occurs with the item count enough to perform long scrolls and seems to be triggered **only** by rapid scrolling. The amount of scrolls required to trigger the issue varies, sometimes it crashes only after 3-4 such iterations.
![Image](https://github.com/user-attachments/assets/c7bdfbe0-1f25-46f4-a447-a2dd72ad4cbc)

- Slow scrolling as well as scrolling with a mouse wheel **does not** seem to cause any issues.
- Similar controls such as `ListView` **do not** seem to cause such issues under the same conditions.

**Exception Message**
`Source object type is not a projected type and does not inherit from a projected type. (Parameter 'value')`

**Stack Trace**
```
at WinRT.CastExtensions.GetRefForObject(Object value)
at WinRT.CastExtensions.As[TInterface](Object value)
at TreeViewScrollingIssue.MainWindow.MainWindow_obj3_Bindings.SetDataRoot(Object newDataRoot) in \\TreeViewScrollingIssue\obj\x64\Debug\net8.0-windows10.0.19041.0\win-x64\MainWindow.g.cs:line 190
at TreeViewScrollingIssue.MainWindow.MainWindow_obj3_Bindings.ProcessBindings(Object item, Int32 itemIndex, Int32 phase, Int32& nextPhase) in \\TreeViewScrollingIssue\obj\x64\Debug\net8.0-windows10.0.19041.0\win-x64\MainWindow.g.cs:line 141
at ABI.Microsoft.UI.Xaml.Markup.IDataTemplateComponent.Do_Abi_ProcessBindings_1(IntPtr thisPtr, IntPtr item, Int32 itemIndex, Int32 phase, Int32* nextPhase)
```

### Steps to reproduce the bug

1. Run the project: https://github.com/datskiy/TreeViewScrollingIssue
2. Start scrolling the `TreeView` quickly all the way up and down sequentially.
3. Observe the unhandled exception and the application crash.

### Expected behavior

The `TreeView` should handle rapid scrolling without crashing the application, like other similar controls.

### Screenshots

**Unhandled exception in VS**
![Image](https://github.com/user-attachments/assets/ce7c9556-ada6-425a-b09a-7321221f2fa6)

### NuGet package version

WinUI 3 - Windows App SDK 1.6.3: 1.6.241114003

### Windows version

Windows 11 (24H2): Build 26100

### Additional context

Source code: https://github.com/datskiy/TreeViewScrollingIssue

**Comment by tpoint75** [comment]
I have a similar issue scrolling fast a listview with more than 10000 items on some pc.
But I could not reproduce it on my development computer.
