### ISSUE TITLE
Could not determine target device configuration on test execution

### ISSUE THREAD

**Issue by ChristianGalla** [microsoft/microsoft-ui-xaml#10261]
### Describe the bug

I was able to execute unit tests using MSTest.

After updating MSTest.TestAdapter and MSTest.TestFramework from 3.6.4 to 3.7.0, test cannot be executed anymore.

Test output:
```
Building Test Projects
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectDataImpl.<GetRemoteMachineAddressAsync>d__36.MoveNext()
Executing all tests in project: AutoStartConfirmTests
========== Starting test run ==========
========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
```

This looks like a regression of 2.2.9: https://github.com/microsoft/microsoft-ui-xaml/issues/6258#issuecomment-1080914310

### Steps to reproduce the bug

1. Checkout my branch https://github.com/ChristianGalla/AutoStartConfirm/tree/mstest-3.7.0
2. Execute the test project

As an alternative the same issue should occur on other test projects that have MSTest.TestAdapter and MSTest.TestFramework installed in version 3.7.0.

### Expected behavior

Tests can be discovered and executed.

### NuGet package version

None

### Additional context

Language: C#
OS: Windows 10 22H2
Framework: .NET 9
Packaging: unpackaged
Windows App SDK version: 1.6.241114003

**Comment by LucaCris** [comment]
Confirmed (SDK 1.6 target Net8):

![Image](https://github.com/user-attachments/assets/ad2d57e9-05ff-4384-b1ad-ac7e57f6bebd)

**Comment by ChristianGalla** [comment]
Looks like it is working now.

In my solution, updating the test framework was not sufficient. I also had to update Visual Studio, create a new test project using the test project template and copy all my old tests.

I compared the new test project with my old one but was not able to isolate a setting that caused this error.
