### ISSUE TITLE
Assign SystemBackdropConfiguration.Theme take no effect and always use SystemBackdropTheme.Dark

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#11535]
### Describe the bug

In Windows App Sdk 1.3, a new way to use Mica or Acrylic is to set the SystemBackdrop of Window.

I created a new class to custom the Acrylic/Mica.
#### Problem 2: Change SystemBackdropConfiguration.Theme & RootLayout's RequestTheme at the same time might throw an ArgumentException. This could not be triggered every time in Demo application, please try click the button in demo multiple times with different pace.

StackTrace
```
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Media.ISystemBackdropOverridesMethods.OnDefaultSystemBackdropConfigurationChanged(IObjectReference _obj, ICompositionSupportsSystemBackdrop target, XamlRoot xamlRoot)
   at Microsoft.UI.Xaml.Media.SystemBackdrop.OnDefaultSystemBackdropConfigurationChanged(ICompositionSupportsSystemBackdrop target, XamlRoot xamlRoot)
   at Microsoft.UI.Xaml.Media.SystemBackdrop.Microsoft.UI.Xaml.Media.ISystemBackdropOverrides.OnDefaultSystemBackdropConfigurationChanged(ICompositionSupportsSystemBackdrop target, XamlRoot xamlRoot)
   at ABI.Microsoft.UI.Xaml.Media.ISystemBackdropOverrides.Do_Abi_OnDefaultSystemBackdropConfigurationChanged_2(IntPtr thisPtr, IntPtr target, IntPtr xamlRoot)
```

### Steps to reproduce the bug

```csharp
namespace Test
{
    internal sealed class AcrylicMaterialBackdrop : SystemBackdrop
    {
        private readonly DesktopAcrylicController AcrylicMaterialController = new DesktopAcrylicController();
        private readonly SystemBackdropConfiguration BackdropConfiguration = new SystemBackdropConfiguration
        {
            IsInputActive = true,
            Theme = SystemBackdropTheme.Dark // Set SystemBackdropTheme.Light takes no effect
        };

        public static bool IsSupported => DesktopAcrylicController.IsSupported();

        protected override void OnTargetConnected(ICompositionSupportsSystemBackdrop connectedTarget, XamlRoot xamlRoot)
        {
            AcrylicMaterialController.AddSystemBackdropTarget(connectedTarget);
            AcrylicMaterialController.SetSystemBackdropConfiguration(BackdropConfiguration);

            base.OnTargetConnected(connectedTarget, xamlRoot);
        }

        protected override void OnTargetDisconnected(ICompositionSupportsSystemBackdrop disconnectedTarget)
        {
            AcrylicMaterialController.RemoveSystemBackdropTarget(disconnectedTarget);

            base.OnTargetDisconnected(disconnectedTarget);
        }
    }
}
```

### Expected behavior

Apply SystemBackdropTheme.Light as expected

### NuGet package version

Windows App Sdk 1.3

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Demo application: 
[BackdropTest.zip](https://github.com/microsoft/WindowsAppSDK/files/11219492/BackdropTest.zip)

**Comment by zhuxb711** [comment]
> > However, docs for SystemBackdrop should mention it or the developer might be very confuse about that.
> 
> Definitely agree :-). I opened [#3589](https://github.com/microsoft/WindowsAppSDK/issues/3589) to track this doc issue.
> 
> > For Problem 2: I overrided OnDefaultSystemBackdropConfigurationChanged and do not trigger this problem any more. But still worth to investigate it.
> 
> Thanks, this is useful information! I agree we need to investigate. I can occasionally repro this crash locally and have dump saved, actively investigating...
> 
> > For Problem 3 - Markup instantiation of <MicaBackdrop>
> 
> This is a known issue; we have a fix candidate for it that we're testing internally. (For full context, in the Feb 15, 2023 WinUI Community Call <discussion #8137>, I incorrectly stated that this scenario works in light of a fix that went into WinAppSDK 1.3 Preview1 release, unfortunately that fix was not complete [fixed the crash, but material was still not getting applied] :-(.)

For problem 2, it seems that when windows using light theme, the `ICompositionSupportsSystemBackdrop target` of `OnDefaultSystemBackdropConfigurationChanged` is null and cause the issue

**Comment by lauren-ciha** [comment]
Thank you for bringing this to our attention. The `SystemBackdropConfiguration` API is a part of WinUI, so I'm transferring this issue to the [WinUI repo](https://github.com/microsoft/microsoft-ui-xaml) where the owning team can take a closer look.
