### ISSUE TITLE
NavigationView.put_SelectedItem exception: The parameter is incorrect. container

### ISSUE THREAD

**Issue by sam-wheat** [microsoft/microsoft-ui-xaml#1200]
Probably related or a dupe of this issue:  https://github.com/microsoft/microsoft-ui-xaml/issues/767

Hopefully this supplies an additional data point.
[KanbanTasker.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3532743/KanbanTasker.zip)

Please run the attached project.  Click the "+" icon on the top left.

		<NavigationView
            x:Name="kanbanNavView"
            Grid.Row="1"
            MenuItemsSource="{x:Bind ViewModel.BoardList, Mode=TwoWay}"
            SelectedItem="{x:Bind ViewModel.CurrentBoard, Mode=TwoWay}"

In MainViewModel:

		public void NewBoardCommandHandler()
        {
            BoardViewModel newBoard = new BoardViewModel(new PresentationBoard(new BoardDTO()));
            CurrentBoard = newBoard;
        }

Exception:

The parameter is incorrect. 

container

   at Windows.UI.Xaml.Controls.NavigationView.put_SelectedItem(Object value)
   at KanbanTasker.MainPage.XamlBindingSetters.Set_Windows_UI_Xaml_Controls_NavigationView_SelectedItem(NavigationView obj, Object value, String targetNullValue)
   at KanbanTasker.MainPage.MainPage_obj1_Bindings.Update_ViewModel_CurrentBoard(BoardViewModel obj, Int32 phase)
   at KanbanTasker.MainPage.MainPage_obj1_Bindings.MainPage_obj1_BindingsTracking.PropertyChanged_ViewModel(Object sender, PropertyChangedEventArgs e)
   at KanbanTasker.Base.Observable.OnPropertyChanged(String propertyName)
   at KanbanTasker.ViewModels.MainViewModel.set_CurrentBoard(BoardViewModel value)
   at KanbanTasker.ViewModels.MainViewModel.NewBoardCommandHandler()
   at KanbanTasker.Base.RelayCommand.Execute(Object parameter)
   at System.Runtime.InteropServices.WindowsRuntime.ICommandToWinRTAdapter.Execute(Object parameter)

**Comment by hjohnson12** [comment]
Originally found in this commit here, which is before changed to MenuItems

https://github.com/hjohnson12/Kanban-Tasker/commit/c7b1a4775e25384666e2a9bc33c682f02441b45c#comments

**Comment by jevansaks** [comment]
@licanhua Can you help take a look at this one too?

**Comment by sam-wheat** [comment]
Thank you!  The first workaround will work fine for the moment.


Sam Wheat
(714)931-7440
sam.wheat@outlook.com
www.samwheat.com<https://www.samwheat.com>
