### ISSUE TITLE
Exception in SelectionModel.SelectRange.

### ISSUE THREAD

**Issue by grokys** [microsoft/microsoft-ui-xaml#1915]
**Describe the bug**

Simple usage of `SelectionModel.SelectRange` throws an exception:

```
Message: 
    Assert.Fail failed. Exception thrown by action on the UI thread: System.Runtime.InteropServices.COMException (0x8000000B): The operation attempted to access data outside the valid range
    
    invalid vector subscript
       at Microsoft.UI.Xaml.Controls.SelectionModel.SelectRange(IndexPath start, IndexPath end)
       at Windows.UI.Xaml.Tests.MUXControls.ApiTests.RepeaterTests.SelectionModelTests.<>c.<SelectRange_Should_Work>b__0_0()
       at MUXControlsTestApp.Utilities.RunOnUIThread.<>c__DisplayClass1_1.<Execute>b__1()
  Stack Trace: 
    Verify.Fail(String message, Object[] args)
    RunOnUIThread.Execute(CoreApplicationView whichView, Action action)
    RunOnUIThread.Execute(Action action)
    SelectionModelTests.SelectRange_Should_Work()
```

**Steps to reproduce the bug**

Unit test demonstrating the issue:

```
        [TestMethod]
        public void SelectRange_Should_Work()
        {
            RunOnUIThread.Execute(() =>
            {
                var target = new SelectionModel();
                var data = CreateNestedData(1, 2, 3);

                target.Source = data;
                target.SelectRange(IndexPath.CreateFrom(0), IndexPath.CreateFrom(1, 1));
            });
        }
```

**Expected behavior**

No exception.

**Version Info**

Current master

**Comment by ranjeshj** [comment]
@grokys  can you please paste how the nested data looks like. Is it a valid path in the nested collection ? If so, it looks like a bug.

**Comment by grokys** [comment]
I added the test above to the `Windows.UI.Xaml.Tests.MUXControls.ApiTests.RepeaterTests.SelectionModelTests` class in the repo, so `CreateNestedData` is the same that's being used in the other unit tests. The data looks like this:

```
[ [0, 1, 2], [3, 4, 5] ]
```

So 1,1 should be a valid index.

```
