### ISSUE TITLE
Cant Install visx on VS 2019

### ISSUE THREAD

**Issue by DwainSnickles** [microsoft/microsoft-ui-xaml#2576]
5/30/2020 6:04:23 AM - Microsoft VSIX Installer
5/30/2020 6:04:23 AM - -------------------------------------------
5/30/2020 6:04:23 AM - vsixinstaller.exe version:
5/30/2020 6:04:23 AM - 16.6.2051
5/30/2020 6:04:23 AM - -------------------------------------------
5/30/2020 6:04:23 AM - Command line parameters:
5/30/2020 6:04:23 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\dwain.DESKTOP-PBV6NB0\Downloads\WinUI.ProjectTemplates.vsix
5/30/2020 6:04:23 AM - -------------------------------------------
5/30/2020 6:04:23 AM - Microsoft VSIX Installer
5/30/2020 6:04:23 AM - -------------------------------------------
5/30/2020 6:04:24 AM - Initializing Install...
5/30/2020 6:04:24 AM - Extension Details...
5/30/2020 6:04:24 AM - 	Identifier         : Microsoft.WinUI.ProjectTemplates
5/30/2020 6:04:24 AM - 	Name               : WinUI 3 Project Templates
5/30/2020 6:04:24 AM - 	Author             : Microsoft
5/30/2020 6:04:24 AM - 	Version            : 3.0.0.2005153
5/30/2020 6:04:24 AM - 	Description        : The Microsoft Windows UI Library (WinUI) Visual Studio extension adds project and item templates to support building WinUI 3 apps and components.
5/30/2020 6:04:24 AM - 	Locale             : en-US
5/30/2020 6:04:24 AM - 	MoreInfoURL        : https://github.com/microsoft/microsoft-ui-xaml/
5/30/2020 6:04:24 AM - 	InstalledByMSI     : False
5/30/2020 6:04:24 AM - 	SupportedFrameworkVersionRange : [4.5,)
5/30/2020 6:04:24 AM - 
5/30/2020 6:04:25 AM - 	SignatureState     : ValidSignature
5/30/2020 6:04:25 AM - 	SignedBy           : Microsoft Corporation
5/30/2020 6:04:25 AM - 	Certificate Info   : 
5/30/2020 6:04:25 AM - 		-------------------------------------------------------
5/30/2020 6:04:25 AM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
5/30/2020 6:04:25 AM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
5/30/2020 6:04:25 AM - 		[Serial Number] : 330000033C51C393599E34695900000000033C
5/30/2020 6:04:25 AM - 		[Not Before]    : 3/11/2020 12:06:39 PM
5/30/2020 6:04:25 AM - 		[Not After]     : 3/5/2021 11:06:39 AM
5/30/2020 6:04:25 AM - 		[Thumbprint]    : F9DFA92ED94D8DFD37D9465D89BBFA260B920287
5/30/2020 6:04:25 AM - 
5/30/2020 6:04:25 AM - 	Supported Products : 
5/30/2020 6:04:25 AM - 		Microsoft.VisualStudio.Community
5/30/2020 6:04:25 AM - 			Version : [16.7,17.0)
5/30/2020 6:04:25 AM - 		Microsoft.VisualStudio.Pro
5/30/2020 6:04:25 AM - 			Version : [16.7,17.0)
5/30/2020 6:04:25 AM - 		Microsoft.VisualStudio.Enterprise
5/30/2020 6:04:25 AM - 			Version : [16.7,17.0)
5/30/2020 6:04:25 AM - 
5/30/2020 6:04:25 AM - 	References         : 
5/30/2020 6:04:25 AM - 	Prerequisites      : 
5/30/2020 6:04:25 AM - 		-------------------------------------------------------
5/30/2020 6:04:25 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
5/30/2020 6:04:25 AM - 		Name         : Visual Studio core editor
5/30/2020 6:04:25 AM - 		Version      : [16.0,17.0)
5/30/2020 6:04:25 AM - 
5/30/2020 6:04:25 AM - 		-------------------------------------------------------
5/30/2020 6:04:25 AM - 		Identifier   : Microsoft.VisualStudio.ComponentGroup.UWP.Support
5/30/2020 6:04:25 AM - 		Name         : Universal Windows Platform tools
5/30/2020 6:04:25 AM - 		Version      : [16.2.29003.222,17.0)
5/30/2020 6:04:25 AM - 
5/30/2020 6:04:25 AM - Signature Details...
5/30/2020 6:04:25 AM - 	Extension is signed with a valid signature.
5/30/2020 6:04:25 AM - 
5/30/2020 6:04:25 AM - Searching for applicable products...
5/30/2020 6:04:25 AM - Found installed product - Global Location
5/30/2020 6:04:25 AM - Found installed product - Visual Studio Enterprise 2019
5/30/2020 6:04:25 AM - Found installed product - Visual Studio Enterprise 2017
5/30/2020 6:04:26 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by DwainSnickles** [comment]
I think its because of my version according to supported products I have 
Version 16.5.5
