### ISSUE TITLE
Unhandled exception on popup open

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#3389]
**Describe the bug**

Such a code causes an unhandled exception

![image](https://user-images.githubusercontent.com/23479280/95386719-625b6300-08f8-11eb-921d-dc49b69ca7b3.png)

**Steps to reproduce the bug**

1. Create a blank WinUI app for desktop
2. Add the following code in MainWindow constructor after InitializeComponent.

```
        var p = new Popup();
        p.Child = new TextBlock() { Text = "Text" };
        p.IsOpen = true;
```

3. Run application

**Version Info**

Windows 10 1903 (OS Build 18362.1082)

**NuGet package version:**

WinUI 3.0.0-preview2.200713.0

**Windows app type:**

| UWP              | Win32            |
| :--------------- | :--------------- |
|| Yes|

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment]
@BorzillaR is this a desktop or UWP application? do you have and stack info you can share?

**Comment by StephenLPeters** [comment]
@codendone putting on rendering because I suspect this is popup related.

**Comment by BorzillaR** [comment]
![image](https://user-images.githubusercontent.com/23479280/95435069-c747a500-095a-11eb-94a4-8160cf3eee85.png)

Stack details:

```
  System.Runtime.InteropServices.COMException
  HResult=0x8000FFFF
  Message=Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
```

**Comment by codendone** [comment]
The error message shown in the output window is "explaining" the error, but we should definitely make some improvements to better expose the error (rather than just seeing the E_UNEXPECTED message in the exception dialog), better explain what needs to be done, and better document this issue.

The problem is that this is a parentless popup, so XAML doesn't know which window to show the popup for. (And it complains even when there is only one to prevent weird behavior of having code stop working when there is more than one window.) There are two possible fixes to this: (1) add the Popup in the Children list of some other element, or (2) set the XamlRoot property to explicitly state what the popup belongs to.

Option (2) provides a trivial fix in your example by adding the second line here:

```
            var p = new Popup();
            p.XamlRoot = this.Content.XamlRoot;
            p.Child = new TextBlock() { Text = "Popup Text" };
            p.IsOpen = true;
````

Note: The XamlRoot needs to be set before setting the popup to IsOpen=true.

**Comment by BorzillaR** [comment]
@codendone, thank you.

I think it is one of the common migration issues from UWP. In WPF the popup is just a standalone window. In UWP there is only one CoreWindow per thread. It is no need to place the popup to the visual tree there. But in WinUI for Desktop popup should be the visual child of any element. We cant get the current window from our class libraries (this is impossible with such architecture) and we cant show popup in the own visual tree as in WPF. So we need to put the popup parent every time we want to show it. The same issue I mentioned is in # 3376 relates to getting the current compositor.

**Comment by sigmarsson** [comment]
Howdy, 

Can you advise on [3741](https://github.com/microsoft/microsoft-ui-xaml/issues/3741) anything ? I face the same exception though having no popup.

**Comment by BorzillaR** [comment]
I am having a try to check this issue in Preview 4.
After this code line

`p.IsOpen = true;`

is executed, all of my windows on desktop are disappearing. The only way to make them visible again is to reboot the PC.

**Comment by codendone** [comment]
I can confirm the crash has not been fixed: it is still necessary to set the XamlRoot property first.

The crash shouldn't be able to cause windows from other apps to disappear. Was the Windows taskbar still visible and functional, or did the entire screen go black? If taskbar was still there, was the Start menu still available, and, if so, did new apps launch correctly?

**Comment by BorzillaR** [comment]
@codendone, start menu and taskbar work as expected and I can even see thumbnail previews. I can launch the other apps through the start menu, but all the new windows become invisible.

**Comment by Bondarenko1990** [comment]
I have error
![image](https://user-images.githubusercontent.com/32612104/171472650-9bee2997-bd54-4214-9486-816da597756c.png)

**Comment by codendone** [comment]
@Bondarenko1990 I believe `this.Content.XamlRoot` will still be null during the constructor. Waiting for `this.Content.Loaded` should work.

**Comment by Bondarenko1990** [comment]
@codendone Thanks

**Comment by MiyamuraMiyako** [comment]
```trace
Application: Kiosk.exe
CoreCLR Version: 9.0.24.26619
.NET Version: 9.0.0-preview.4.24266.19
Description: The process was terminated due to an unhandled exception.
Stack:
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.SetWindowPos(System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, Int32, Int32, Int32, Int32, Int32)
   at System.Windows.Interop.HwndSource.Resize(System.Windows.Size)
   at System.Windows.Interop.HwndSource.OnLayoutUpdated(System.Object, System.EventArgs)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(System.Windows.Media.Visual)
   at System.Windows.Interop.HwndSource.set_RootVisual(System.Windows.Media.Visual)
   at System.Windows.Controls.Primitives.Popup.SetRootVisualToPopupRoot()
   at System.Windows.Controls.Primitives.Popup.CreateWindow(Boolean)
   at System.Windows.Controls.Primitives.Popup.OnIsOpenChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at System.Windows.DependencyObject.SetValue(System.Windows.DependencyProperty, System.Object)
   at System.Windows.Controls.Primitives.Popup.set_IsOpen(Boolean)

   at Kiosk.UI.Pages.V2.InputUsrInfoPage.ButtonMobile_Click(System.Object, System.Windows.RoutedEventArgs)
   
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainToMouse(System.Windows.Input.StagingAreaInputItem)
   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainUpToTouch(System.Windows.Input.StylusWisp.WispStylusDevice, System.Windows.Input.StagingAreaInputItem)
   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainToTouch(System.Windows.Input.ProcessInputEventArgs, System.Windows.Input.StylusEventArgs)
   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainToOther(System.Windows.Input.ProcessInputEventArgs)
   at System.Windows.Input.StylusWisp.WispLogic.PostProcessInput(System.Object, System.Windows.Input.ProcessInputEventArgs)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(System.Tuple`2<System.Windows.Input.ProcessInputEventHandler,System.Delegate[]>, System.Windows.Input.ProcessInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.StylusWisp.WispLogic.InputManagerProcessInput(System.Object)
   at System.Windows.Input.StylusWisp.WispLogic.PreProcessInput(System.Object, System.Windows.Input.PreProcessInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run()
   at Kiosk.App.Main()
```

@StephenLPeters @codendone  I'm also having this issue, occasionally Popup causes crashes when open.
