### ISSUE TITLE
Error when showing ContentDialog in desktop app

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#3678]
**Describe the bug**

`ArgumentException` is thrown when attempting to open a `ContentDialog` in a WinUI3 Desktop app.

**Steps to reproduce the bug**

1. Create a new blank WinUI3 Desktop app
2. Add this class

```cs
public sealed partial class MyCustomDialog : ContentDialog
{
    public MyCustomDialog()
    {
        this.InitializeComponent();
    }
}
```

3. With this XAML

```xml
<ContentDialog
    x:Class="App206.MyCustomDialog"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    Title="TITLE"
    PrimaryButtonText="Button1"
    SecondaryButtonText="Button2">

    <Grid>
        <TextBlock>hello</TextBlock>
    </Grid>
</ContentDialog>
```
4. Change `myButton_Click` in `MainPage.xaml.cs` to be:

```cs
private async void myButton_Click(object sender, RoutedEventArgs e)
{
    var dialog = new MyCustomDialog();
    await dialog.ShowAsync();
}
```

5. Run the app and click the button.

```ascii
System.ArgumentException
  HResult=0x80070057
  Message=Value does not fall within the expected range.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IContentDialog.global::Microsoft.UI.Xaml.Controls.IContentDialog.ShowAsync()
   at Microsoft.UI.Xaml.Controls.ContentDialog.ShowAsync()
   at App206.MainWindow.<myButton_Click>d__1.MoveNext() in C:\Users\matt\source\repos\App206\App206\App206\MainWindow.xaml.cs:line 35
```

**Expected behavior**
dialog show be shown without error.

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.WinUI 3.0.0-preview3.201113.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20175.1000)              | Yes   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

This works without issue in a UWP app (WinUI2 and 3)

**Comment by mrlacey** [comment]
X-Ref https://github.com/microsoft/microsoft-ui-xaml/issues/1679 which discusses other `ContentDialog` related issues and possible improvements.

**Comment by sylveon** [comment]
I believe you're forgetting to set the XamlRoot

**Comment by mrlacey** [comment]
> I believe you're forgetting to set the XamlRoot

Yes, this was the issue.

Will update the OP to reflect the need not to crash and provide a more descriptive error message.

**Comment by mrlacey** [comment]
At the very least this needs a more helpful error message.

This gives no clue as to the cause and so doesn't help solve the cause of the crash.

> System.ArgumentException -  Message=Value does not fall within the expected range.

**Comment by nickrandolph** [comment]
Let's bump the priority on this issue - it's seriously nuts that developers have to set xamlroot on a dialog.
