### ISSUE TITLE
WebAuthenticationBroker.AuthenticateAsync throws COMException

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#3692]
**Describe the bug**
On WinUI 3 preview 3 for Desktop, when calling WebAuthenticationBroker.AuthenticateAsync, I get the following exception:
System.Runtime.InteropServices.COMException (0x800706BD): There are no remote procedure calls active on this thread. (0x800706BD)   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.Security.Authentication.Web.IWebAuthenticationBrokerStatics.global::Windows.Security.Authentication.Web.IWebAuthenticationBrokerStatics.AuthenticateAsync(WebAuthenticationOptions options, Uri requestUri, Uri callbackUri)
   at Windows.Security.Authentication.Web.WebAuthenticationBroker.AuthenticateAsync(WebAuthenticationOptions options, Uri requestUri, Uri callbackUri)

This code previously worked in a UWP application without problems.

**Steps to reproduce the bug**
1. Call WebAuthenticationBroker.AuthenticateAsync

Example:
 var result = await WebAuthenticationBroker.AuthenticateAsync(
                WebAuthenticationOptions.None,
                authorizeUri, redirectUri);

**Expected behavior**
I would expect the Microsoft authentication dialog to appear.

**Version Info**
NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No (=works fine)  |Yes (=exception) |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |Yes |

**Comment by stevenbrix** [comment]
Adding some folks who may know if this API works in Win32 or not. @MikeHillberg @jonwis @oldnewthing
