### ISSUE TITLE
Error while loading project properties - WinUI 3 preview 3 - Packaged Desktop App

### ISSUE THREAD

**Issue by sjb-sjb** [microsoft/microsoft-ui-xaml#4013]
Using: Visual Studio Version 16.9.0 Preview 2.0, WinUI 3 preview 3

Steps to reproduce: 
- Create a new project using the "Blank App, Packaged (WinUI in Desktop)" template.
- Right-click on the Package project and select "Properties" at the bottom of the context menu.

Expected: should open the properties window for the project
Actual: an exception message occurs as follows:

**An error occurred while loading the project properties editor**

System.ArgumentException: Incorrect number of property values given the dimension matrix
Parameter name: properties
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.PropertyContext..ctor(ConfigurationMatrix configurationMatrix, ImmutableArray`1 properties, IPropertyValueChangeHandler changeHandler, JoinableTaskFactory jtf)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertiesEditor.<.ctor>g__CreatePropertyContext|0_2(IProject project, JoinableTaskFactory jtf)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertiesEditor.<>c__DisplayClass0_0.<<-ctor>g__LoadPropertyContextAsync|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertiesEditor.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.AsyncLoadContent.<>c__DisplayClass0_0.<<Initialize>b__0>d.MoveNext()

**Comment by StephenLPeters** [comment]
@alwu-msft FYI

**Comment by alwu-msft** [comment]
@sjb-sjb Thanks for your report! From the exception call stack, this appears to be an issue residing in the VS Project System rather than WinUI. Could you open a new issue in [dotnet/project-system](https://github.com/dotnet/project-system) so that the appropriate team can take ownership of the investigation? I suspect that they'll want additional details about the repro as well (e.g. how consistently does this occur? Does it persist through VS restarts or only the first time you try to edit the project properties after project creation?).

**Comment by marb2000** [comment]
Closing this issue given @sjb-sjb routed it to dotnet per @alwu-msft recommendation,
