### ISSUE TITLE
Change theme programmatically in WinUI 3 preview 3 desktop application

### ISSUE THREAD

**Issue by arivoir** [microsoft/microsoft-ui-xaml#4105]
I'm trying to change the theme of the app programmatically

`App.Current.RequestedTheme = themes.SelectedIndex == 0 ? ApplicationTheme.Dark : ApplicationTheme.Light;`

but I'm getting an exception

> System.NotSupportedException
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplication.global::Microsoft.UI.Xaml.IApplication.set_RequestedTheme(ApplicationTheme value)
   at Microsoft.UI.Xaml.Application.set_RequestedTheme(ApplicationTheme value)
   at FlexGridExplorer.MainWindow.OnSelectionChanged(Object sender, SelectionChangedEventArgs e) in C:\Projects\GrapeCity\c1-netcore\WinUI\Samples\Grid\FlexGridExplorer\FlexGridExplorer\MainWindow.xaml.cs:line 26
   at ABI.Microsoft.UI.Xaml.Controls.SelectionChangedEventHandler.<>c__DisplayClass10_0.<Do_Abi_Invoke>b__0(SelectionChangedEventHandler invoke)
   at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)
   at ABI.Microsoft.UI.Xaml.Controls.SelectionChangedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)

I also tried changing the theme of the root element of the main windows, but the controls don't update accordingly.

**Comment by marb2000** [comment]
Hi @arivoir, use the UIElement's RequestedTheme property instead of Application.RequestedTheme  to change the theme dynamically in Desktop WinUI 3.

Here you can find sample: 

https://github.com/microsoft/WinUI-3-Demos/blob/081c65edefd38514e867a71f1b54f910647257f4/src/Build2020Demo/DemoBuildCs/DemoBuildCs/DemoBuildCs/MainWindow.xaml.cs#L138 

Hope this helps. Closing the discussion.

**Comment by arivoir** [comment]
That worked, but before I needed to add a background to the root element. Apparently changing the theme of the root doesn't change the background, which I guess belong to the window

`Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"`

**Comment by OphirBleicher** [comment]
How can I adjust the system caption buttons to the theme?
