### ISSUE TITLE
[Preview 4] FileOpenPicker PickMultipleFilesAsync Break

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#4198]
**Describe the bug**

The FileOpenPicker in WinUI3 Preview4 Desktop sample solution breaks and closes the application when trying to open multiple items. Exception details below in the last section.

**Steps to reproduce the bug**

1. Clone the [WinUI3 Preview4 Problems FilePicker repository](https://github.com/eleanorleffler/WinUI3Preview4_Problems_FileOpenPicker). 
2. Go to the FilePickerWinUIPreview4 folder.
3. Open the FilePickerWinUIPreview4 solution in Visual Studio 2019 Preview.
4. Build and run with Debug x64.
5. Click the second / bottom button "FileOpenPicker: Multiple Files". (The first button should work as expected.)
6. Select one or more files.
7. Click "Open". Crash should occur.

**Expected behavior**

We expect the application to display the path of the selected file(s) or folder.

We expect the FileOpenPicker to allow the user to select multiple files as it does in UWP.

**Screenshots**

![ExpectedBehavior](https://user-images.githubusercontent.com/9272634/107994895-338a8300-6fa3-11eb-8e1d-4a42ec3ce9a9.PNG)

![CurrentBehavior2](https://user-images.githubusercontent.com/9272634/107994919-3eddae80-6fa3-11eb-9aa6-6a34eb30d416.PNG)

Screenshot#1a and 1b - Current Behavior (Single File working and Crash Error Message)

![CurrentBehavior1](https://user-images.githubusercontent.com/9272634/107994904-36857380-6fa3-11eb-94f2-bed6d016faa1.PNG)

Screenshot#2 - Expected Behavior (File paths of selected files)

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4]

Targeting:
Target: Universal Windows
Target version: Windows 10, version 1809 (10.0; Build 17763)
Min version: Windows 10, version 1803 (10.0; Build 17134)

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| 		Yes 	   |  				  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | 						 |
| May 2020 Update (19041)            | 						 |
| November 2019 Update (18363)       | 						 |
| May 2019 Update (18362)            | 						 |
| October 2018 Update (17763)        | 			Yes			 |
| April 2018 Update (17134)          | 						 |
| Fall Creators Update (16299)       | 						 |
| Creators Update (15063)            | 						 |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | 		Yes			|
| Xbox               | 					|
| Surface Hub        | 					|
| IoT                | 					|

**Additional context**

Exception Details

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at WinRT.SingleInterfaceOptimizedObject..ctor(Type type, IObjectReference objRef)
   at Windows.Storage.Pickers.FilePickerSelectedFilesArray.<.ctor>b__8_1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Windows.Storage.Pickers.FilePickerSelectedFilesArray.AsInternal(InterfaceTag`1 _)
   at Windows.Storage.Pickers.FilePickerSelectedFilesArray.GetEnumerator()
   at FileOpenPickerWinUIPreview4.MainWindow.<fileOpenPickerMultipleButton_Click>d__2.MoveNext() in \FileOpenPickerWinUIPreview4\FileOpenPickerWinUIPreview4\MainWindow.xaml.cs:line 60

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
COMException: The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))

**Comment by StephenLPeters** [comment]
@Scottj1s and @stevenbrix is this cswinrt related?

**Comment by codendone** [comment]
See #4192 for more information on why this doesn't work and the workaround.

**Comment by marb2000** [comment]
@eleanorleffler thanks opening the bug and share the code. I could repro this. 

I noticed that the doc of this API has the UWP label. I don't know if this means that this API won't work in Win32 apps.

> Shows the file picker so that the user can pick multiple files. (UWP app)

I need help from the Project Reunion folks, this API is out of the WinUI domain. @jonwis, can you help us to know what is happening here? 

We get: 
>COMException: The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))

Below you can find the code snipped:


```CS
 public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
        }

        private async void fileOpenPickerMultipleButton_Click(object sender, RoutedEventArgs e)
        {
            FileOpenPicker picker = new FileOpenPicker();

            IInitializeWithWindow initializeWithWindowWrapper = picker.As<IInitializeWithWindow>();
            var hwnd = this.As<IWindowNative>().WindowHandle;
            initializeWithWindowWrapper.Initialize(hwnd);

            picker.ViewMode = PickerViewMode.List;
            picker.SuggestedStartLocation = PickerLocationId.Desktop;
            picker.FileTypeFilter.Add(".txt");

            var filesToOpen = await picker.PickMultipleFilesAsync();
            string text = string.Empty;
            foreach (StorageFile storageFile in filesToOpen)
            {
                text += storageFile.Path + Environment.NewLine;
            }
            fileOpenPickerMultipleTextBlock.Text = text;
        }
        public static void InitializeWithWindow(Object obj, Window window)
        {
            // When running on win32, FileOpenPicker needs to know the top-level hwnd via IInitializeWithWindow::Initialize.
            if (Window.Current == null)
            {
                IInitializeWithWindow initializeWithWindowWrapper = obj.As<IInitializeWithWindow>();
                var hwnd = window.As<IWindowNative>().WindowHandle;
                initializeWithWindowWrapper.Initialize(hwnd);
            }
        }

    }

    [ComImport]
    [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IInitializeWithWindow
    {
        void Initialize([In] IntPtr hwnd);
    }
    [ComImport]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    [Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
    internal interface IWindowNative
    {
        IntPtr WindowHandle { get; }
    }
```

**Comment by marb2000** [comment]
Transferring issue to the Project Reunion. It's not a WinUI issue.
