### ISSUE TITLE
Setting Storyboard.BeginTime throws InvalidCastException

### ISSUE THREAD

**Issue by billhenn** [microsoft/microsoft-ui-xaml#4461]
**Describe the bug**
Set the `Storyboard.BeginTime` property and you get:

```
System.InvalidCastException
  HResult=0x80004002
  Message=Interface not registered

  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.IObjectReference.As[T](Guid iid)
   at WinRT.IObjectReference.As[T]()
   at WinRT.MarshalInterface`1.CreateMarshaler(T value)
   at ABI.Microsoft.UI.Xaml.Media.Animation.ITimeline.global::Microsoft.UI.Xaml.Media.Animation.ITimeline.set_BeginTime(Nullable`1 value)
   at Microsoft.UI.Xaml.Media.Animation.Timeline.set_BeginTime(Nullable`1 value)
   at WinUITestApp.MainWindow.myButton_Click(Object sender, RoutedEventArgs e) in S:\Code\Test\Actipro\WinUITestApp\WinUITestApp\MainWindow.xaml.cs:line 33
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.<>c__DisplayClass10_0.<Do_Abi_Invoke>b__0(RoutedEventHandler invoke)
   at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```

**Steps to reproduce the bug**

```
var storyboard = new Storyboard();
storyboard.BeginTime = TimeSpan.Zero;
```

**Expected behavior**
It should work.

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |  Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by ranjeshj** [comment]
@Scottj1s Looks like this could be a CSWinrt issue.

**Comment by Scottj1s** [comment]
Yes, this was a regression in C#/WinRT deciding whether to implement IReference, which overlooked a few value types like TimeSpan.  Fix will be available in the next public release of C#/WinRT, 1.1.4.
https://github.com/microsoft/CsWinRT/pull/770

**Comment by BorzillaR** [comment]
I reproduced this issue with a TimeLine.BeginTime property on the latest Project Reunion SDK (0.5.0)

**Comment by manodasanW** [comment]
@BorzillaR Can you try updating your NET 5 SDK to the version that came out today (5.0.202).  That has the C#/WinRT fix for this issue.

**Comment by BorzillaR** [comment]
@manodasanW, thank you!
I have updated NET 5 SDK to v. 5.0.202. All works as expected now.
