### ISSUE TITLE
Setting Application.Current.RequestedTheme throws exception

### ISSUE THREAD

**Issue by billhenn** [microsoft/microsoft-ui-xaml#4474]
**Describe the bug**
Setting `Application.Current.RequestedTheme` at run-time to alter the app's light/dark theme throws this exception:
```
System.NotSupportedException
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplication.global::Microsoft.UI.Xaml.IApplication.set_RequestedTheme(ApplicationTheme value)
   at Microsoft.UI.Xaml.Application.set_RequestedTheme(ApplicationTheme value)
   at TestApp.RootWindow.OnThemeMenuFlyoutItemClick(Object sender, RoutedEventArgs e) in S:\Code\TestApp\Views\RootWindow.xaml.cs:line 71
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.<>c__DisplayClass10_0.<Do_Abi_Invoke>b__0(RoutedEventHandler invoke)
   at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```

Setting the `RequestedTheme` property on the root `Grid` in my `Window` succeeds.  But I want to change it app-wide, not only on this window.

**Steps to reproduce the bug**

Use this code to reproduce:
```
Application.Current.RequestedTheme = ApplicationTheme.Dark;
```

**Expected behavior**

No exception and the app theme should toggle to the selected theme.

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by ranjeshj** [comment]
@llongley @codendone as FYI

**Comment by codendone** [comment]
This is currently by design. It is a little hidden down in the Remarks section of [the documentation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.requestedtheme?view=winrt-19041):

> The theme can only be set when the app is started, not while it's running. Attempting to set RequestedTheme while the app is running throws an exception (NotSupportedException for Microsoft .NET code). ...
>
> You can change specific theme values at run-time after Application.RequestedTheme is applied, if you use the FrameworkElement.RequestedTheme property and sets values on specific elements in the UI.

The error message could certainly be better -- a problem we have for all errors right now. This error will be much easier to understand when the code is finally open source, since you'd then be able to see this code comment at the source of the exception:
```
    // RequestedTheme cannot be set after app.xaml has been loaded.
```

**Comment by billhenn** [comment]
@codendone Thanks, I apologize I didn't see that remark before.  The more descriptive error message would certainly help prevent confusion on this, and as you said, error messages really need to be more detailed across the board.

I would really ask that you improve this to support app-wide theme changes without having to restart the app.  All popular modern apps support instant live theme changes between variations of light and dark themes without having to restart, and it's kind of an expected app capability at this point.  Not having support for that in a "modern" UI platform is very disappointing.  Thanks for listening!

**Comment by codendone** [comment]
I believe this restriction exists simply because way back in Windows 8 when the RequestedTheme support was implemented there weren't available resources to also support dynamic changes. Adding that support could be done in the future, so I'm marking this as a future feature proposal.

**Comment by billhenn** [comment]
Thank you @codendone, much appreciated.

**Comment by jtorjo** [comment]
Guys, can you please please please add just a tad of description in the exception, when you throw it?
I wanted to bang my head against the wall on this one

**Comment by ajsuydam** [comment]
A potentially dumb question: if runtime switching isn't supported, how does task manager do it? Or notepad? Both support runtime switching, and they're both using WinUI 3.

**Comment by Lightczx** [comment]
place this line of code inside your App's OnLaunched method to set `m_isRequestedThemeSettable` to true
``` c#
*(bool*)(((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(IApplicationIID).ThisPtr + 0x118U) = true;
```
(Tested and works in WASDK 1.6.3)

---
Additional Context:
https://github.com/microsoft/WindowsAppSDK/discussions/4710#discussioncomment-10741712

**Comment by ghost1372** [comment]
> place this line of code inside your App's OnLaunched method to set `m_isRequestedThemeSettable` to true
> 
> *(bool*)(((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(IApplicationIID).ThisPtr + 0x118U) = true;
> (Tested and works in WASDK 1.6.3)
> 
> Additional Context: [microsoft/WindowsAppSDK#4710 (comment)](https://github.com/microsoft/WindowsAppSDK/discussions/4710#discussioncomment-10741712)

what is IApplicationIID ?
![Image](https://github.com/user-attachments/assets/46b81faf-8a5f-4f26-853f-066fe0a9d126)

**Comment by Lightczx** [comment]
> what is IApplicationIID ?

@ghost1372  My bad, you can find through looking the code decompiled by VS.

There is a `Make___objRef_global__Microsoft_UI_Xaml_IApplication` method in `Application`

![Image](https://github.com/user-attachments/assets/065821d5-5bb7-4abb-9ef0-ce52f60d7032)

And finally get this

![Image](https://github.com/user-attachments/assets/d8f14cb4-9aa0-479b-ba2f-50f84445236e)

**Comment by ghost1372** [comment]
> > what is IApplicationIID ?
> 
> [@ghost1372](https://github.com/ghost1372) My bad, you can find through looking the code decompiled by VS.
> 
> There is a `Make___objRef_global__Microsoft_UI_Xaml_IApplication` method in `Application`
> 
> ![Image](https://github.com/user-attachments/assets/065821d5-5bb7-4abb-9ef0-ce52f60d7032)
> 
> And finally get this
> 
> ![Image](https://github.com/user-attachments/assets/d8f14cb4-9aa0-479b-ba2f-50f84445236e)

thank you now its working fine

complete code:

unsafe
{
    *(bool*)(((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(IID).ThisPtr + 0x118U) = true;
}

public static ref readonly Guid IID
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    get
    {
        return ref Unsafe.As<byte, Guid>(ref MemoryMarshal.GetReference((ReadOnlySpan<byte>)new byte[16]
        {
            231, 244, 168, 6, 70, 17, 175, 85, 130, 13,
            235, 213, 86, 67, 176, 33
        }));
    }
}
