### ISSUE TITLE
Calling FocusManager.TryMoveFocus(FocusNavigationDirection.Next) throws COMException

### ISSUE THREAD

**Issue by DHancock** [microsoft/microsoft-ui-xaml#5593]
**Describe the bug**

The app has several text boxes each with the max length property set to be a single character. When the user enters a valid character the text changed event handler for the text box calls FocusManager.TryMoveFocus() to attempt to set the focus to the next text box, ready for the users next input. TryMoveFocus() throws the exception:
```
System.Runtime.InteropServices.COMException
  HResult=0x8000FFFF
  Message=Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Input.IFocusManagerStatics.global::Microsoft.UI.Xaml.Input.IFocusManagerStatics.TryMoveFocus(FocusNavigationDirection focusNavigationDirection)
   at Microsoft.UI.Xaml.Input.FocusManager.TryMoveFocus(FocusNavigationDirection focusNavigationDirection)
   at FocusTraversalBug.MainWindow.TextBox_TextChanged(Object sender, TextChangedEventArgs e) in C:\Users\David\source\repos\FocusTraversalBug\FocusTraversalBug\FocusTraversalBug\MainWindow.xaml.cs:line 23
   at ABI.Microsoft.UI.Xaml.Controls.TextChangedEventHandler.<>c__DisplayClass10_0.<Do_Abi_Invoke>b__0(TextChangedEventHandler invoke)
   at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)
   at ABI.Microsoft.UI.Xaml.Controls.TextChangedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```

**Steps to reproduce the bug**

I've attached a minimal repro solution:

[FocusTraversalBug.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6909281/FocusTraversalBug.zip)

**Expected behavior**

TryMoveFocus() shouldn't throw (even if I'm doing something daft)

**Version Info**

NuGet package version: 

WinUI 3 - Project Reunion 0.8.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| 21H1 (19043.1110) | Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

I'm porting a WPF app and the equivilent feature worked ok when called in the text changed event
```
textbox.MoveFocus(new TraversalRequest(FocusNavigationDirection.Next));
```

**Comment by codendone** [comment]
In non-UWP scenarios it is required to use FocusManager.TryMoveFocus(FocusNavigationDirection,FindNextElementOptions) so that FindNextElementOptions can provide an appropriate SearchRoot to work with.

Of course, just throwing an exception isn't great behavior. There should also be an OriginateError string which may be visible in debugger output depending on your debugger setup, but that isn't very discoverable. We likely need to remove this API at some point so that only the long form version exists.

**Comment by DHancock** [comment]
I had tried using FindNextElementOptions in both the async version and normal TryMoveFocus() calls in my real project and it also failed (so I didn't both mentioning it). I have now found that supplying a _SearchRoot_ does however work in the in the minimal repro project supplied above. So it seems the failure is dependant on its location with in the visual tree. This simple cases works:

**Window -> StackPanel -> TextBoxes**

but fails for:

**Window -> NavigationView -> Frame -> Page -> StackPanel -> TextBoxes**

The exception is different though. It now throws:
```
System.ArgumentException
  HResult=0x80070057
  Message=Value does not fall within the expected range.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Input.IFocusManagerStatics.global::Microsoft.UI.Xaml.Input.IFocusManagerStatics.TryMoveFocus(FocusNavigationDirection focusNavigationDirection, FindNextElementOptions focusNavigationOptions)
   at Microsoft.UI.Xaml.Input.FocusManager.TryMoveFocus(FocusNavigationDirection focusNavigationDirection, FindNextElementOptions focusNavigationOptions)
   at FocusTraversalBug.Page1.TextBox_TextChanged(Object sender, TextChangedEventArgs e) in C:\Users\David\source\repos\FocusTraversalBug\FocusTraversalBug\FocusTraversalBug\Page1.xaml.cs:line 30
   at ABI.Microsoft.UI.Xaml.Controls.TextChangedEventHandler.<>c__DisplayClass10_0.<Do_Abi_Invoke>b__0(TextChangedEventHandler invoke)
   at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)
   at ABI.Microsoft.UI.Xaml.Controls.TextChangedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```

I call the focus manager using the code below, where "tb" is one of the text boxes:

```
   FindNextElementOptions fneo = new() { SearchRoot = tb.Parent };
   _ = FocusManager.TryMoveFocus(FocusNavigationDirection.Next, fneo);
```

I've updated the minimal repro project so that it now shows the problem:

[FocusTraversalBug.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6974867/FocusTraversalBug.zip)

**Comment by DHancock** [comment]
Thanks for the update, that fixes it. FocusManager does seem to have a coupe of "trip hazards", although I should have read the manual in a bit more detail...
