### ISSUE TITLE
Error running published and installed WinUI3 application

### ISSUE THREAD

**Issue by jmiddour** [microsoft/microsoft-ui-xaml#5673]
**Describe the bug**
When running a winui3 application targeting win10-x64 running the package project from inside visual studio works just fine.  However, when attempting to run the application after being published and installed on a machine, the application fails with this error:
Application: MyApplication.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at Microsoft.UI.Xaml.Application._IApplicationStatics..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at MyApplication.Program.Main(String[] args)

**Expected behavior**
I expect to be able to run a published app, ideally from the exe.

**Version Info**
Project Reunion version 0.8.1
WinUi, desktop application
Windows 10 20H2

**Comment by jmiddour** [comment]
And this is the DevOps pipeline task I'm using to build the msix:
`    - task: MSBuild@1
      displayName: Build for $(BuildConfiguration)
      inputs:
        solution: "$(PackageProjectPath)/*.wapproj"
        platform: x64
        msbuildArguments:  '/t:Restore;Build /p:UapAppxPackageBuildMode=$(MsixBuildMode) /p:AppxBundle=Always /p:GenerateAppInstallerFile=$(MsixGenerateAppInstaller) 
        /p:AppInstallerUri=$(DistributionUrl) /p:SelfContained=True /p:RuntimeIdentifier=win10-x64 /p:PublishReadyToRun=True /p:PublishProtocol=FileSystem'
        configuration: release`

**Comment by StephenLPeters** [comment]
@alwu-msft FYI

**Comment by Marv51** [comment]
Are you sure you are starting the **packaging** project and **not** the project with all your source files?

**Comment by ghost1372** [comment]
@jmiddour Is the internet active on another system? Before installing app, I noticed that a framework is being installed from the store.

**Comment by jmiddour** [comment]
@Marv51 -- This is after the application is deployed and installed.  Not within visual studio.  It works just fine when running the package project inside visual studio.

@ghost1372  -- yes the machines that I have tried this on do have internet connection, but nothing seems to be attempting to install from the store either.
