### ISSUE TITLE
XAML Parse Exception

### ISSUE THREAD

**Issue by JanRajnoha** [microsoft/microsoft-ui-xaml#5808]
**Describe the bug**
App is throwing XAML Parse Exception with stack trace:
`   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStatics.global::Microsoft.UI.Xaml.IApplicationStatics.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at CloudCash.Client.Controls.BusyOverlay.InitializeComponent() in C:\Users\JR\source\repos\JanRajnoha\CloudCash\src\CloudCash.Client\obj\x86\Debug\net5.0-windows10.0.19041.0\Controls\BusyOverlay.g.i.cs:line 37
   at CloudCash.Client.Controls.BusyOverlay.DoInitialize(Int32 attempt) in C:\Users\JR\source\repos\JanRajnoha\CloudCash\src\CloudCash.Client\Controls\BusyOverlay.xaml.cs:line 43`

and message:
Failed to assign to property 'Microsoft.UI.Xaml.Media.AcrylicBrush.TintColor'. [Line: 18 Position: 27]

Code:
![image](https://user-images.githubusercontent.com/16069721/131564277-13b12db9-737d-41be-ad17-7ee850aebdfa.png)

**Expected behavior**
No exception

**Version Info**
Windows App SDK - 0.8.2
CommunityToolkit.WinUI.Controls - 7.0.3
WinUI app packaged

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (Windows 11 - dev)              | Yes   |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
similar error to this: https://github.com/microsoft/microsoft-ui-xaml/issues/5814 however the circumstances aren't the same at all.  This is using a winui3 nuget packages that is using the winui2 framework package.. might or might not be related.
