### ISSUE TITLE
Blank app WAP WinUI 3 Desktop template does not work out of the box

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#5898]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blank-app-WAP-WinUI-3-Desktop-template-d/1530690)._

---
1. Create a new [Experimental] Blank App. Packaged with WAP (WinUI 3 in Desktop)
2. Don't change the default minimum and target windows versions.
3. Hit F5 to run it.
4. You will get 2 compiler errors as in the screenshot: CS8773	Feature 'file-scoped namespace' is not available in C# 9.0. Please use language version 10.0 or greater.
5. Fix those errors by changing the namespaces to the old format (without the ;).
6. Hit F5 to run it.
7. You will get: System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance()
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at MyChessSolverPro.Program.Main(String[] args) in D:\PROJECTS\MyChessSolverPro\MyChessSolverPro\obj\x86\Debug\net5.0-windows10.0.19041.0\App.g.i.cs:line 26

This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

Expected behavior is for a template to work out of the box.
That means correct .NET version, Correct C# version, and no runtime exceptions!!!

---
#### Danny Cohen on 9/15/2021, 11:17 AM: 

<p>Deploy seems to work. Maybe this kind of template should not run under DEBUG?<br>
Another problem with this template:<br>
Project - Properties - Build - General - Warning Level, I can’t select anything from the pull down menu.<br>
It shows my selection for a second and than reverts to empty.</p>

#### Danny Cohen on 9/15/2021, 11:54 AM: 

<p>I found my mistake, the Package Project should be selected before hitting F5 to run in DEBUG.<br>
However, the template is based on .Net 5 instead of .Net 6 and the pull down menu bug still exists.</p>

#### Feedback Bot on 9/16/2021, 01:04 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
@alwu-msft FYI

**Comment by evelynwu-msft** [comment]
Closing as there is nothing to fix; this was user error.
