### ISSUE TITLE
Polyline Points throws exception

### ISSUE THREAD

**Issue by nzstevem** [microsoft/microsoft-ui-xaml#5962]
**Describe the bug**

It appears that any access to a Polyline.Points collection throws an exception in 0.8.4 (see below) in WinUI.

The simplest case I've found is...

 Polyline myPolyline = new Polyline();
 myPolyline.Points.Clear();

Other elements such as Line work as expected. I discovered the issue when trying to add points initialing thinking the issue was related to the Windows.Foundation.Point structure but no. It's more fundamental.

Simple demonstration project attached. Press the button.

"System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for '<SignatureCache>System.Collections.Generic.IList`1<Windows.Foundation.Point>' threw an exception.
  Source=Microsoft.WinUI
  StackTrace:
   at <GuidPatcherImplementationDetails>.<IIDData>System.Collections.Generic.IList`1<Windows.Foundation.Point>()
   at Microsoft.UI.Xaml.Media.PointCollection..ctor(IObjectReference objRef)
   at WinRT.DefaultComWrappers.CreateObject(IObjectReference objRef)
   at WinRT.DefaultComWrappers.CreateObject(IntPtr externalComObject, CreateObjectFlags flags)
   at System.Runtime.InteropServices.ComWrappers.CallCreateObject(ComWrappersScenario scenario, ComWrappers comWrappersImpl, IntPtr externalComObject, CreateObjectFlags flags)
   at System.Runtime.InteropServices.ComWrappers.TryGetOrCreateObjectForComInstanceInternal(ObjectHandleOnStack comWrappersImpl, Int64 wrapperId, IntPtr externalComObject, IntPtr innerMaybe, CreateObjectFlags flags, ObjectHandleOnStack wrapper, ObjectHandleOnStack retValue)
   at System.Runtime.InteropServices.ComWrappers.TryGetOrCreateObjectForComInstanceInternal(ComWrappers impl, IntPtr externalComObject, IntPtr innerMaybe, CreateObjectFlags flags, Object wrapperMaybe, Object& retValue)
   at System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(IntPtr externalComObject, CreateObjectFlags flags)
   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr, Boolean tryUseCache)
   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr)
   at WinRT.MarshalInspectable`1.FromAbi(IntPtr ptr)
   at Microsoft.UI.Xaml.Media.PointCollection.FromAbi(IntPtr thisPtr)
   at ABI.Microsoft.UI.Xaml.Media.PointCollection.FromAbi(IntPtr thisPtr)
   at ABI.Microsoft.UI.Xaml.Shapes.IPolyline.global::Microsoft.UI.Xaml.Shapes.IPolyline.get_Points()
   at Microsoft.UI.Xaml.Shapes.Polyline.get_Points()

Inner Exception 1:
TypeLoadException: Could not load type 'ABI.Windows.Foundation.Point' from assembly 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b'.

**Expected behavior**

No exception

**Screenshots**
![image](https://user-images.githubusercontent.com/29415301/134745136-68bab9a6-bca6-44f3-af17-55248d32e161.png)

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |

**Additional context**

**Comment by nzstevem** [comment]
[TestPolyLine.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7228976/TestPolyLine.zip)

**Comment by nzstevem** [comment]
Closed in error.
Test project attached.
[TestPolyLine.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7228981/TestPolyLine.zip)
r

**Comment by nzstevem** [comment]
Versions are Win10 19043, and WinUI 0.8.4. Net 5 & 6 both exhibit same issue.

WinUI 0.8.1 works as expected.

**Comment by nzstevem** [comment]
Same problem with the Microsoft.WindowsAppSDK preview1

**Comment by nzstevem** [comment]
WindowsappSDK 1.0.0-**preview2** clears this issue for me. thanks
