### ISSUE TITLE
Proposal: Include WinUI 3 test projects (as already exist for standard UWP apps)

### ISSUE THREAD

**Issue by marcelwgn** [microsoft/microsoft-ui-xaml#6258]
# Proposal: Include WinUI 3 test projects (as already exist for standard UWP apps)

## Summary

For the UWP runtime, there are dedicated test app project templates included in Visual Studio. For WinUI 3, we have project templates for apps, libraries and component libraries, however no template that one can use to load WinUI 3 projects and write tests against them.

## Rationale

* Make it easier to write tests for WinUI 3 projects

## Scope

| Capability | Priority |
| :---------- | :------- |
| Include console test app that can include WinUI 3 libraries and includes MSTest | Must |
| Include test app with a window and page that can include WinUI 3 libraries and includes MSTest | Must |
| Include console test app that can include WinUI 3 libraries and includes NUnit or XUnit | Could |
| Include test app with a window and page that can include WinUI 3 libraries and includes NUnit or XUnit | Must |

**Comment by Zachael** [comment]
error CS7069: Reference to type 'DispatcherQueue' claims it is defined in 'Microsoft.WinUI', but it could not be found
when trying to implement
https://devblogs.microsoft.com/ifdef-windows/winui-desktop-unit-tests/
with the following

Microsoft.WindowsAppSDK 1.0.0
Microsoft.Windows.SDK.BuildTools 10.0.22000.194

MSTest.TestAdapter 2.2.7
MSTest.TestFramework 2.2.7
Microsoft.TestPlatform.TestHost 17.00.0

https://github.com/microsoft/testfx/issues/993

**Comment by StephenLPeters** [comment]
@Zachael it has moved to Microsoft.UI.Dispatching namespace: https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.dispatching?view=winui-3.0

**Comment by StephenLPeters** [comment]
@evelynwu-msft FYI

**Comment by chingucoding** [comment]
For what it's worth, I created my own templates ([Visualstudio extension](https://marketplace.visualstudio.com/items?itemName=chingucoding.winuiunittesttemplates)/[Extension source code](https://github.com/chingucoding/WinUI-UnitTest-Templates)). While they have certain limitations, hopefully they might help other folks get started.

**Comment by kmgallahan** [comment]
@chingucoding Do you get pile of these errors when using windowless testing?

```
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectDataImpl.<GetRemoteMachineAddressAsync>d__35.MoveNext()
```

Also, does your ability to run tests fail if you upgrade to `MSTest.TestAdapter` & `MSTest.TestFramework` 2.2.9 preview? (if you use those)

VS 17.2.0 Preview 2.1

**Comment by chingucoding** [comment]
Yes @kmgallahan I can confirm that they also happen on my machine. Regarding the EnvDTE things, I think that this was not the case with VS 2019 (but don't quote me on that). The MSTest version has always been a problem, some versions just don't work or just work partially.

**Comment by kla50** [comment]
I used the procedures in Alexandre's blog and I'm getting the EnvDTE errors, too.   When I run the tests they simply don't run.  I'm using VS 2022 17.2.0 Preview 2.1, 2.2.9-preview-20220210-07 of the test packages, Windows App SDK 1.1.0-preview1, SDK BuildTools 10.0.22581-preview, and Windows 11 Pro 22H2 22581.200.

**Comment by kmgallahan** [comment]
@kla50 Downgrading the test packages to 2.2.8 should allow them to run.

**Comment by kla50** [comment]
@kmgallahan , That did it.  Thanks!

**Comment by kla50** [comment]
Has anyone had problems writing arbitrary text to a test method's log file?  I had used Console.WriteLine in the past, but it is not currently working.  After I run the test, I use the "Open test log" menu item from the test methods context menu to review the log.  None of the Console.WriteLine messages are present.  Is this an issue with the current state of WinUI unit testing?

**Comment by kla50** [comment]
I've followed the procedures on Alexandre Z's blog to create a WinUI 3 Desktop Unit Test project.  My initial issue was that the tests would not run, and this was resolved by downgrading MSTest.TestAdapter and MSTest.TestFramework to 2.2.8.  And the unit tests were running.  Then something changed (OS update, VS update, WinUI package update) and the tests stopped running again - Test Explorer just lists them as not run with a couple of warnings:

[4/26/2022 10:03:35.521 AM] [Warning] [MSTest][Discovery][F:\Source\_WinUI\LearnWinUI3_04\Libraries\CommonTest\bin\x64\Debug\net6.0-windows10.0.19041.0\CommonTest.dll] Failed to discover tests from assembly F:\Source\_WinUI\LearnWinUI3_04\Libraries\CommonTest\bin\x64\Debug\net6.0-windows10.0.19041.0\CommonTest.dll. Reason:File does not exist: F:\Source\_WinUI\LearnWinUI3_04\Libraries\CommonTest\bin\x64\Debug\net6.0-windows10.0.19041.0\CommonTest.dll
[4/26/2022 10:03:35.522 AM] [Warning] No test is available in F:\Source\_WinUI\LearnWinUI3_04\Libraries\CommonTest\bin\x64\Debug\net6.0-windows10.0.19041.0\CommonTest.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

I've verified that the test DLL actually exists and Test Explorer is finding and presenting the tests without issue.  I've been trying different permutations of MSTest.TestAdapter, MSTest.TestFramework, and Microsoft.TestPlatform.TestHost versions but haven't found anything that allows the tests to run.  I've also tried changing unit test projects platform and test processor architecture from AnyCPU and Auto to x64, but it didn't work either.

System details (I'm listing the versions of the test packages that had previously worked):
Windows 11 Pro 21H2 22000.652
Visual Studio Community 2022 (64-bit) version 17.2.0 Preview 4.0
Microsoft.TestPlatform 17.2.0-preview-20220401-07
MSTest.TestAdapter 2.2.8
MSTest.TestFramework 2.2.8
Microsoft.Windows.SDK.BuildTools 10.0.22598-preview
Microsoft.WindowsAppSDK 1.1.0-preview2

Any ideas on how to get unit tests to run again?

**Comment by kla50** [comment]
Hmm... I guess I should have waited a little longer before posting this.  Looks like 2.2.10 just got release today.  Now tests are running again.

System Details:
Windows 11 Pro 21H2 22000.652
Visual Studio Community 2022 (64-bit) version 17.2.0 Preview 4.0
Microsoft.TestPlatform 17.2.0-preview-20220401-08
MSTest.TestAdapter 2.2.10
MSTest.TestFramework 2.2.10
Microsoft.Windows.SDK.BuildTools 10.0.22598-preview
Microsoft.WindowsAppSDK 1.1.0-preview2

**Comment by kla50** [comment]
If I create a test project using the "MSTest Test Project" template, debugging the unit test works - execution stops at breakpoints.  But when I try to debug a WinUI 3.0 test project created using the procedures in Alexandre Z's blog, debugging the unit test does not work - breakpoints are ignored.

System details:
Windows 11 Pro 21H2 22000.652 (with all updates)
Visual Studio Community 2022 (64-bit) version 17.2.0 Preview 4.0
Microsoft.TestPlatform 17.2.0-preview-20220401-08
MSTest.TestAdapter 2.2.10
MSTest.TestFramework 2.2.10
Microsoft.Windows.SDK.BuildTools 10.0.22598-preview
Microsoft.WindowsAppSDK 1.1.0-preview2

Anybody else having this problem?  Any ideas on how to get debugging WinUI 3 unit tests to work?

**Comment by kmgallahan** [comment]
For me being unable to stop at (or even place) breakpoints in a WinUI 3 project is not exclusive to testing. 

https://github.com/microsoft/microsoft-ui-xaml/issues/6980#issuecomment-1104078087

**Comment by kla50** [comment]
@kmgallahan, So far, I've been able to debug the actual WinUI 3.0 app and the locals have been working for me.  However, I'm in the WinUI 3 learning phase, so my apps are very simple and am working on getting base class library things like options, logging, and exception handling ironed out to my liking.  I'm starting to do the same as you and refactor any non-WinUI dependent code into .NET 6 libraries so they can be unit tested more effectively.

**Comment by chingucoding** [comment]
@Scottj1s FYI

**Comment by marcelwgn** [comment]
Closing since there is a Test App project template now.
