### ISSUE TITLE
App crash when using configuration name different from Debug or Release

### ISSUE THREAD

**Issue by romulo-rosinha** [Microsoft/microsoft-ui-xaml#634]
**Describe the bug**
Not sure this is a bug or just me doing something wrong, could not find documentation regarding this, but I get the following app crash when using a Configuration name different from Debug or Release:

> Faulting application name: App1.exe, version: 1.0.0.0, time stamp: 0x5bb69bfe
> Faulting module name: Windows.UI.Xaml.dll, version: 10.0.17763.404, time stamp: 0x5c3c199a
> Exception code: 0xc000027b
> Fault offset: 0x008dc0f1
> Faulting process id: 0x28bc
> Faulting application start time: 0x01d4ff7fbe41260f
> Faulting application path: C:\xxxxx\WinUIConfig\App1\bin\x86\Debug1\AppX\App1.exe
> Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
> Report Id: d999fdc1-4bb6-46d0-9e39-8aaf0168a949
> Faulting package full name: 797cbdfa-8cfb-4c0f-9e19-79943324e67e_1.0.0.0_x86__wgcfbsqfkre0m
> Faulting package-relative application ID: App

**Steps to reproduce the bug**
Open attached project [WinUIConfig.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3132571/WinUIConfig.zip) and try to run the app using configuration __Debug1__ 
and platform __x86__. __Debug1__ is the same __Debug__ default configuration with a different name. The app should crash almost immediately.

Here is debug output from when the app crashes:

> Exception thrown at 0x75E8C6F2 in App1.exe: Microsoft C++ exception: EETypeLoadException at memory location 0x06C7D19C.
'App1.exe' (Win32): Loaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Runtime.WindowsRuntime.dll'. 
'App1.exe' (Win32): Unloaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Runtime.WindowsRuntime.dll'
'App1.exe' (Win32): Loaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Runtime.WindowsRuntime.dll'. 
'App1.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Runtime.WindowsRuntime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown at 0x75E8C6F2 in App1.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown: 'System.TypeLoadException' in App1.exe
Exception thrown at 0x75E8C6F2 (KernelBase.dll) in App1.exe: WinRT originate error - 0x80131522 : 'System.TypeLoadException: Could not find Windows Runtime type 'Microsoft.UI.Xaml.Controls.XamlControlsResources'.
   at App1.App1_XamlTypeInfo.XamlTypeInfoProvider.InitTypeTables()
   at App1.App1_XamlTypeInfo.XamlTypeInfoProvider.LookupTypeIndexByName(String typeName)
   at App1.App1_XamlTypeInfo.XamlTypeInfoProvider.GetXamlTypeByName(String typeName)
   at App1.App1_XamlTypeInfo.XamlMetaDataProvider.GetXamlType(String fullName)
   at App1.App.GetXamlType(String fullName)'.
'App1.exe' (Win32): Loaded 'C:\Windows\SysWOW64\userenv.dll'. Cannot find or open the PDB file.
'App1.exe' (Win32): Loaded 'C:\Windows\SysWOW64\profext.dll'. Cannot find or open the PDB file.
'App1.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\profext.dll'
'App1.exe' (Win32): Loaded 'C:\Windows\SysWOW64\profext.dll'. Cannot find or open the PDB file.
Exception thrown at 0x75E8C6F2 (KernelBase.dll) in App1.exe: WinRT originate error - 0x802B000A : 'Cannot deserialize XBF metadata type list as 'XamlControlsResources' was not found in namespace 'Microsoft.UI.Xaml.Controls'. [Line: 0 Position: 0]'.
Windows.UI.Xaml.dll!046F1727: (caller: 0438AD7D) Exception(1) tid(3470) 80004005 Unspecified error
Exception thrown at 0x75E8C6F2 in App1.exe: Microsoft C++ exception: wil::ResultException at memory location 0x06C7DEB0.
Exception thrown at 0x75E8C6F2 in App1.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Windows.UI.Xaml.dll!046F243C: (caller: 0451975E) ReturnHr(1) tid(3470) 80004005 Unspecified error
    Msg:[Windows.UI.Xaml.dll!046F1727: (caller: 0438AD7D) Exception(1) tid(3470) 80004005 Unspecified error
] 
'App1.exe' (Win32): Loaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Diagnostics.Debug.dll'. 
'App1.exe' (Win32): Unloaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Diagnostics.Debug.dll'
'App1.exe' (Win32): Loaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Diagnostics.Debug.dll'. 
'App1.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Diagnostics.Debug.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

App runs fine if using configuration __Debug__.

**Expected behavior**
App does not crash.

**Version Info**
NuGet package version: Microsoft.UI.Xaml 2.1.190405004.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |   |
| October 2018 Update (17763)   | Yes   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |   |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional Context**
Not sure it matters, but I noticed the generated file __XamlTypeInfo.g.cs__ is much larger when using __Debug1__ (38KB) than when using __Debug__ (6KB) .

**Comment by jevansaks** [comment]
@rbrid can you investigate this? Sounds like the app's AppxManifest.xml doesn't have a PackageDependency for Microsoft.UI.Xaml.2.1 based on the error message, but I don't know why the different configurations would be a problem.

**Comment by RichPrism** [comment]
@jevansaks Your hypothesis is correct.  I was having the exact same problem as reported, so I switched from my custom configuration back to Release, and the problem disappeared.  I then edited the Package.appxmanifest file, adding the package dependency for Microsoft.UI.Xaml.2.1 to the Dependencies section. I switched to my custom configuration and rebuilt.  My app ran without encountering the reported problem.

**Comment by chingucoding** [comment]
What area is causing this problem given that it was a missing depency in the appxmanifest? Is this a VS issue or a Nuget issue? If this isn't an issue with the WinUI nuget package itsself (which seems to be the case based on the workaround/fix), should this be marked external or closed? @ranjeshj @StephenLPeters Your thoughts?
