### ISSUE TITLE
Create controls based on ComboBox

### ISSUE THREAD

**Issue by Hazest** [microsoft/microsoft-ui-xaml#6453]
### Describe the bug

I try override _ComboBox_ and create own Select control. I have created in the same way control for _TextBox_ and _Buttos_.  

### Steps to reproduce the bug

SelectField.xaml.cs:
![image](https://user-images.githubusercontent.com/95860477/145397186-3075eee4-40a3-4623-973d-62c7461d9cf7.png)

SelectField.xaml:
![image](https://user-images.githubusercontent.com/95860477/145399086-8e3c6ff6-276c-4634-bc33-54d2c45c2931.png)

Call:
![image](https://user-images.githubusercontent.com/95860477/145397563-67a16591-f954-48ac-af01-8e34b62841f6.png)

Why i try open window with this control. I see that exception:

   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStatics.global::Microsoft.UI.Xaml.IApplicationStatics.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at XXX.Controls.Selects.SelectField.InitializeComponent() in C:\_projects\XXX\obj\x64\Debug\net5.0-windows10.0.19041.0\Controls\Selects\SelectField.g.i.cs:line 37

![image](https://user-images.githubusercontent.com/95860477/145398806-540b25d1-0547-490c-bee5-8110f419ccc4.png)

### Expected behavior

Should display control

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2020 Update (19041)

### Additional context

I want to customize this control to add my own logic.

**Comment by WalkaZxamlem** [comment]
Hello, I've just came across same problem. Any updates on that issue?

**Comment by StephenLPeters** [comment]
@RealTommyKlein can you weigh in?
