### ISSUE TITLE
Microsoft.UI.Windowing.DisplayArea.FindAll iterator throws "Invalid Cast"

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#6454]
### Describe the bug

When using the `Microsoft.UI.Windowing.DisplayArea.FindAll` method, the returned collection fails to be iterated but throws an exception.

### Steps to reproduce the bug

1. Create a new `Blank App, Packaged (WinUI 3 in Desktop)` C# project
2. Add this code to MainWindow `var displays = Microsoft.UI.Windowing.DisplayArea.FindAll();`
3. Try and iterate the returned collection (foreach or ToArray)
4. Observe exception thrown when run: 

### Expected behavior

Exception thrown:
"Specified cast is not valid."
StackTrace:
```
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at WinRT.IWinRTObject.IsInterfaceImplementedFallback(RuntimeTypeHandle interfaceType, Boolean throwIfNotImplemented)
   at WinRT.IWinRTObject.System.Runtime.InteropServices.IDynamicInterfaceCastable.IsInterfaceImplemented(RuntimeTypeHandle interfaceType, Boolean throwIfNotImplemented)
   at System.Runtime.InteropServices.DynamicInterfaceCastableHelpers.IsInterfaceImplemented(IDynamicInterfaceCastable castable, RuntimeType interfaceType, Boolean throwIfNotImplemented)
   at System.Runtime.CompilerServices.CastHelpers.ChkCastAny(Void* toTypeHnd, Object obj)
   at ABI.System.Collections.Generic.IEnumerable`1.<>c__DisplayClass11_0.<_FromIterable>b__0()
   at WinRT.IWinRTObject.<>c__DisplayClass13_0.<GetOrCreateTypeHelperData>b__0(RuntimeTypeHandle type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at WinRT.IWinRTObject.GetOrCreateTypeHelperData(RuntimeTypeHandle type, Func`1 helperDataFactory)
   at ABI.System.Collections.Generic.IEnumerable`1._FromIterable(IWinRTObject _this)
   at ABI.System.Collections.Generic.IEnumerable`1.global::System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at App69.MainWindow..ctor() in E:\sources.tmp\App69\App69\MainWindow.xaml.cs:line 32
```

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 22000.318

### Additional context

As an alternative, you can use PInvoke to get the information, albeit this is a lot more cumbersome:
https://github.com/dotMorten/WinUIEx/blob/3b779e5421960357d88ac8c2145d25a9dd13233c/src/WinUIEx/MonitorInfo.cs

**Comment by apchee** [comment]
I have the same issue.

**Comment by MarkBrainfire** [comment]
I also experienced this same bug.

**Comment by szblajos** [comment]
Yes, this issue still exists, but DisplayAreaWatcher works as expected so its relatively easy to make a workaround until this is fixed.

1. Make your class Implement IDisposable interface
2. Declare a collection e.g an ObservableCollection that holds DisplayArea data.
3. Manage the collection with DisplayAreaWatcher and its events. (Display_Added, Display_Removed)
4. Stop watcher when your class is disposing

My example:
```
public class DisplayManager: IDisposable
{
 	
    private ObservableCollection<DisplayArea> displayAreas;
    private DisplayAreaWatcher watcher;

    DisplayManager()
    {
        DisplayAreas = new ObservableCollection<DisplayArea>();
        watcher = DisplayArea.CreateWatcher();
        watcher.Added += Display_Added;
        watcher.Removed += Display_Removed;
        watcher.Start();
    }	

    private void Display_Added(DisplayAreaWatcher sender, DisplayArea args)
    {
        DisplayAreas.Add(args);
    }

    private void Display_Removed(DisplayAreaWatcher sender, DisplayArea args)
    {
        DisplayAreas.Remove(args);
    }

    public void Dispose()
    {
        watcher.Stop();
        watcher = null;
    }

}
```

**Comment by deepthi-msft** [comment]
@Scottj1s /@angelazhangmsft I think this is CSWinRT issue:
https://github.com/microsoft/CsWinRT/issues/747

**Comment by dotMorten** [comment]
Still an issue in v1.3.230724000:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/1378165/837d8711-f999-469c-a155-d850a8a826da)

**Comment by deepthi-msft** [comment]
@manodasanW this is the same issue as:
https://github.com/microsoft/CsWinRT/issues/747

**Comment by dotMorten** [comment]
@deepthi-msft Different issue (albeit perhaps same root cause).

**Comment by ArensT** [comment]
Another simple workaround:

```c#
var displayAreas = Microsoft.UI.Windowing.DisplayArea.FindAll();

for (int i = 0; i < displayAreas.Count; i++)
{
    Debug.WriteLine("X: " + displayAreas[i].WorkArea.X.ToString());
}
```
