### ISSUE TITLE
VS17.1prv1.1: can't get it to load / build / run without fatal error

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6590]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS171prv11:-cant-get-it-to-load--bui/1587564)._

---
Trying to get GraphicsControls.Sample/WinUI solution to run 'out of the box' ... fails

1- update to prv1.1
2- open VS no code
3- clone https://github.com/dotnet/Microsoft.Maui.Graphics.Controls ( https://github.com/dotnet/Microsoft.Maui.Graphics.Controls.git )
3a- show solution in folder view
4- open solution
5- builds with 2 success / 1 fatal error
6- fails to run

Microsoft.Maui.Graphics.Controls\src\GraphicsControls.Sample\GraphicsControls.Sample.WinUI\Platforms\Windows\App.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "951971EB0FD76E1BB164DD7F3AEE76909251B0B4CCF80BA70880B78181EF8417"

Here's the error message:

System.ArgumentException
  HResult=0x80070057
  Message=Unable to create a wrapper object. The WinRT object 2076297225104 has type Microsoft.UI.Dispatching.DispatcherQueue which cannot be assigned to type Microsoft.UI.Dispatching.DispatcherQueue
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr, Boolean tryUseCache)
   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr, Boolean tryUseCache)
   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr)
   at WinRT.MarshalInspectable`1.FromAbi(IntPtr ptr)
   at Microsoft.UI.Dispatching.DispatcherQueue.FromAbi(IntPtr thisPtr)
   at ABI. Microsoft.UI.Dispatching.DispatcherQueue.FromAbi(IntPtr thisPtr)
   at ABI. Microsoft.UI.Dispatching.IDispatcherQueueStatics.global::Microsoft.UI.Dispatching.IDispatcherQueueStatics.GetForCurrentThread()
   at Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread()
   at GraphicsControls.Sample.WinUI.Program.<>c.<Main>b__0_0(ApplicationInitializationCallbackParams p) in C:\Users\giebi\Source\Repos\Microsoft.Maui.Graphics.Controls\src\GraphicsControls.Sample\GraphicsControls.Sample.WinUI\obj\Debug\net6.0-windows10.0.19041\win-x64\Platforms\Windows\App.g.i.cs:line 27
   at ABI. Microsoft.UI.Xaml.ApplicationInitializationCallback.<>c__DisplayClass10_0. <Do_Abi_Invoke>b__0(ApplicationInitializationCallback invoke)
   at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)
   at ABI. Microsoft.UI.Xaml.ApplicationInitializationCallback.Do_Abi_Invoke(IntPtr thisPtr, IntPtr p)

----------------
Here the Log file:

=====================
11/17/2021 10:20:03 AM
Recoverable
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.ProjectSystem.MefExtensions.GetExportedValueOrDefault[T](ExportProvider exportProvider)
   at Microsoft.VisualStudio.ProjectSystem.AbstractActiveConfiguredValue`1.Initialize()
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposed.EnsureInitialized(Boolean allowInitializing)
   at Microsoft.VisualStudio.ProjectSystem.AbstractActiveConfiguredValue`1.get_Value()
   at Microsoft.VisualStudio.ProjectSystem.VS.Build.Diagnostics.IncrementalBuildFailureDetector.ProjectChecker.<>c__DisplayClass8_0. <<OnProjectBuildCompleted>g__CheckAsync|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Build.Diagnostics.IncrementalBuildFailureDetector.ProjectChecker.<>c__DisplayClass8_0. <<OnProjectBuildCompleted>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.<>c__DisplayClass31_0. <<Fork>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0. <Guard>g__Action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.ProjectSystem.MefExtensions.GetExportedValueOrDefault[T](ExportProvider exportProvider)
   at Microsoft.VisualStudio.ProjectSystem.AbstractActiveConfiguredValue`1.Initialize()
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposed.EnsureInitialized(Boolean allowInitializing)
   at Microsoft.VisualStudio.ProjectSystem.AbstractActiveConfiguredValue`1.get_Value()
   at Microsoft.VisualStudio.ProjectSystem.VS.Build.Diagnostics.IncrementalBuildFailureDetector.ProjectChecker.<>c__DisplayClass8_0. <<OnProjectBuildCompleted>g__CheckAsync|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Build.Diagnostics.IncrementalBuildFailureDetector.ProjectChecker.<>c__DisplayClass8_0. <<OnProjectBuildCompleted>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.<>c__DisplayClass31_0. <<Fork>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0. <Guard>g__Action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================

---
#### Feedback Bot on 11/17/2021, 10:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
@jfversluis I think this issue should have been directed to https://github.com/dotnet/Microsoft.Maui.Graphics.Controls repro instead of our repro. I'm going to close this as external but you may want to open an issue on your end.

**Comment by jfversluis** [comment]
Thanks for the ping @StephenLPeters !

@jsuarezruiz ?
