### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by Arcalise08** [microsoft/microsoft-ui-xaml#6735]
### Describe the bug

Publishing an unpackaged winUI 3 project yields an exe that causes an error on run. Event viewer logs below

```
Application: TestProj.exe
CoreCLR Version: 6.0.222.6406
.NET Version: 6.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Dll was not found.
   at TestProj.Program.XamlCheckProcessRequirements()
   at TestProj.Program.Main(String[] args) in C:\Users\KyleEstes\Desktop\projects\TestProj\TestProj\obj\x64\Release\net6.0-windows10.0.19041.0\win-x64\App.g.i.cs:line 28
```

This is a bare project using the Blank (Run In Desktop) template from windows app sdk c# VS2022 Templates.

Here is the csproj

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>TestProj</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;</RuntimeIdentifiers>
    <PublishProfile>win10-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
	<WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>
	<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
	<DisableMsixProjectCapabilityAddedByProject>true</DisableMsixProjectCapabilityAddedByProject>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22000.194" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!-- Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
       Tools extension to be activated for this project even if the Windows App SDK Nuget
       package has not yet been restored -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnablePreviewMsixTooling)'=='true'">
    <ProjectCapability Include="Msix"/>
  </ItemGroup>
</Project>
```

### Steps to reproduce the bug

1. Create Blank (Run in Desktop)
2. Publish app
3. attempt to run .exe from publish

### Expected behavior

The application starts

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

**Comment by StephenLPeters** [comment]
same as https://github.com/microsoft/microsoft-ui-xaml/issues/6740

**Comment by bpulliam** [comment]
Closing duplicate issues. Please continue the discussion on #6740
