### ISSUE TITLE
[WinUI3 Unpackaged] TargetInvocationException when creating an OverlappedPresenter

### ISSUE THREAD

**Issue by DominicMaas** [microsoft/microsoft-ui-xaml#6765]
### Describe the bug

The following code:

```csharp
var presenter = OverlappedPresenter.CreateForContextMenu();
```

when added to a to a WinUI 3 Unpackaged application throws the following exception:

```
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
An exception of type 'System.Reflection.TargetInvocationException' occurred in System.Private.CoreLib.dll but was not handled in user code

at System.RuntimeType.CreateInstanceOfT()
at System.Activator.CreateInstance[T]()
at WinRT.WeakLazy`1.get_Value()
at Microsoft.UI.Windowing.OverlappedPresenter._IOverlappedPresenterStatics.get_Instance()
at Microsoft.UI.Windowing.OverlappedPresenter.CreateForContextMenu()
at OverlappedPresenterBug.MainWindow..ctor() in C:\\Development\\OverlappedPresenterBug\\MainWindow.xaml.cs:line 28
at OverlappedPresenterBug.App.OnLaunched(LaunchActivatedEventArgs args) in C:\\Development\\OverlappedPresenterBug\\App.xaml.cs:line 44
at Microsoft.UI.Xaml.Application.Microsoft.UI.Xaml.IApplicationOverrides.OnLaunched(LaunchActivatedEventArgs args)
at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)"
```

This works perfectly fine when creating a packaged MSIX application.

### Steps to reproduce the bug

1. Create a new WinUI3 app (Blank App, Packaged (WinUI 3 in Desktop)
2. Add `<WindowsPackageType>None</WindowsPackageType>` to csproj file
3. Add the following to the MainWindow constructor 

```csharp
var presenter = OverlappedPresenter.CreateForContextMenu();
```

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

**Comment by castorix** [comment]
Same problem as [#6353](https://github.com/microsoft/microsoft-ui-xaml/issues/6353)
You must use a Manifest (tested on Windows 10 21H1)

**Comment by DominicMaas** [comment]
That worked. Thanks!

(wish that was documented somewhere....)
