### ISSUE TITLE
Various Exceptions When Setting Value of Xaml Resource in C#

### ISSUE THREAD

**Issue by sharpninja** [microsoft/microsoft-ui-xaml#6784]
### Describe the bug

When attempting to widen the `ContentDialog` by setting a new value for `ContentDialogMaxWidth`, ab `COMException` or `AccessViolationException` exception is always thrown.

### Steps to reproduce the bug

Attempt microsoft/WindowsAppSDK#1:

```cs
var width = App.Current.Resources["ContentDialogMaxWidth"];

if (width is double)
{
    App.Current.Resources["ContentDialogMaxWidth"] = 1280.0;
}

```

Exception Thrown:
```
System.Runtime.InteropServices.COMException
  HResult=0x800F1000
  Message=No installed components were detected.

  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.DelegateExtensions.DynamicInvokeAbi(Delegate del, Object[] invoke_params)
   at ABI.System.Collections.Generic.IDictionary`2.global::Windows.Foundation.Collections.IMap<K,V>.Insert(K key, V value)
   at ABI.System.Collections.Generic.IDictionary`2.FromAbiHelper.Insert(IMap`2 _this, K key, V value)
   at ABI.System.Collections.Generic.IDictionary`2.FromAbiHelper.Indexer_Set(K key, V value)
   at ABI.System.Collections.Generic.IDictionary`2.FromAbiHelper.set_Item(K key, V value)
   at ABI.System.Collections.Generic.IDictionary`2.global::System.Collections.Generic.IDictionary<K,V>.set_Item(K key, V value)
   at Microsoft.UI.Xaml.ResourceDictionary.set_Item(Object key, Object value)
   at Homeschool.MainPage.<.ctor>b__4_0(Object sender, RoutedEventArgs args) in C:\GitHub\Homeschool.Net6\UI\Homeschool\MainPage.xaml.cs:line 29
   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.<>c__DisplayClass10_0.<Do_Abi_Invoke>b__0(RoutedEventHandler invoke)
   at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```

Attempt microsoft/WindowsAppSDK#2:

```cs
var width = App.Current.Resources["ContentDialogMaxWidth"];

if (width is double)
{
    App.Current.Resources.SetValue(ContentDialog.MaxWidthProperty, 1280);
}
```

Results:

```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

This one feels like it's trying to evaluate the dependency property instead of using it as a key.

### Expected behavior

The default value for `MaxWidth` of `ContentDialog` would be updated.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx), Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

### Additional context

This is a symptom.  The root problem is not being able to use `MinWidth`, `Width` or `MaxWidth` on a `ContentDialog`.

**Comment by StephenLPeters** [comment]
Resources in dictionaries are keyed to by strings, not by DependencyProperties: https://github.com/microsoft/microsoft-ui-xaml/blob/8faca194c943df556afa1f0f8a44ad9697cb43ad/dev/CommonStyles/ContentDialog_themeresources.xaml#L20  If you want to override this resource I would recomend that you do so in a markup file.  If you must do it in code behind you should be using the string "ContentDialogMaxWidth" as the key.

**Comment by sharpninja** [comment]
> 

```cs
var width = App.Current.Resources["ContentDialogMaxWidth"];

if (width is double)
{
    App.Current.Resources.SetValue(ContentDialog.MaxWidthProperty, 1280);
}
```

This compiles, there is no overload that takes a string.

**Comment by sharpninja** [comment]
> Resources in dictionaries are keyed to by strings, not by DependencyProperties:
> 
> https://github.com/microsoft/microsoft-ui-xaml/blob/8faca194c943df556afa1f0f8a44ad9697cb43ad/dev/CommonStyles/ContentDialog_themeresources.xaml#L20
> 
> If you must do it in code behind you should be using the string "ContentDialogMaxWidth" as the key.

That is precisely what I did as attempt #1 that generates the first exception I posted.

**Comment by sharpninja** [comment]
Maybe I'm just experiencing a more fundamental issue.  The COM layer in WinUI3 seems.... ___brittle___.  Even when my apps run correctly, tons of COM errors (usually that the requested COM service is missing) fill the output.

**Comment by ojhad** [comment]
@StephenLPeters is correct in that the best way to do this is through XAML. However, it does seem like the first example should work. This could be a CSWinRT bug? Moving to team-Markup.
