### ISSUE TITLE
Question: Prism Dialog :: "Cannot locate resource from 'ms-appx:///Prism.Uno/Services/Dialogs/DialogWindow.xaml'."

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#7067]
How can I add Prism resource to an unpackaged application ? Currently it cannot locate that Prism related resource. 

![image](https://user-images.githubusercontent.com/43340959/167117148-9c19b44c-2cf4-4b69-8262-38b8b1261991.png)

![image](https://user-images.githubusercontent.com/43340959/167116726-39b20934-eddf-41cb-bff5-efa04fee04d0.png)

```
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStatics.global::Microsoft.UI.Xaml.IApplicationStatics.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Prism.Services.Dialogs.DialogWindow.InitializeComponent() in C:\Users\gombata-locadmin\source\repos\Prism\src\Uno\Prism.Uno\obj\Prism.Uno.WinUI\Debug\net5.0-windows10.0.18362\Services\Dialogs\DialogWindow.g.i.cs:line 37
   at Prism.Services.Dialogs.DialogWindow..ctor() in C:\Users\gombata-locadmin\source\repos\Prism\src\Uno\Prism.Uno\Services\Dialogs\DialogWindow.xaml.cs:line 27
```

**Comment by sigmarsson** [comment]
This is an unpackaged application, Perhaps that is root cause it tries to locate the resource in a package? 

`"Cannot locate resource from '**ms-appx:///**Prism.Uno/Services/Dialogs/DialogWindow.xaml'."`

I open a dialog like this :

![image](https://user-images.githubusercontent.com/43340959/169344477-8ccbc104-ab7f-4c50-a3ad-c11be1ca37a6.png)

**Comment by sigmarsson** [comment]
reported this issue to Prism as well. The ```ContentDialog``` opens with ```.ShowAsync()```. Is it more WinUI or Prism issue ? 
https://github.com/PrismLibrary/Prism/discussions/2693

**Comment by sigmarsson** [comment]
By the way, why does it require the ```DialogWindow.xaml``` if the dialog itself was registered as dialog rather window ? 

` containerRegistry.RegisterDialog<ExportView>(RegionNames.Export);`

**Comment by sigmarsson** [comment]
Prism dialog service fails to show the ```ContentDialog``` however .```ShowAsync()``` cop with that;

![image](https://user-images.githubusercontent.com/43340959/172048341-0dd97778-0d2a-4c26-af7f-ddae7d03ddf1.png)

Here is the exception : 


`at WinRT.ExceptionHelpers.g__Throw|20_0(Int32 hr) at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.LoadComponent(IObjectReference _obj, Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation) at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation) at Prism.Services.Dialogs.DialogWindow.InitializeComponent() at Prism.Services.Dialogs.DialogWindow..ctor() at lambda_method41(Closure , IResolverContext ) at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 355 at DryIoc.Resolver.Resolve(IResolver resolver, Type serviceType, Object[] args, IfUnresolved ifUnresolved, Type requiredServiceType, Object serviceKey) in /_/src/DryIoc/Container.cs:line 8299 at Prism.DryIoc.DryIocContainerExtension.Resolve(Type type, ValueTuple`2[] parameters)`

**Comment by sigmarsson** [comment]
Perhaps it is again an issue related to an unpackaged app ? ```Prism``` tries to initialize a component but WinUI is unable to accomplish because it is unpackaged ? Please advise how to fix .
