### ISSUE TITLE
WinUI 3 'XAML parsing failed' when adding <TextBox/>

### ISSUE THREAD

**Issue by vsedge** [microsoft/microsoft-ui-xaml#8075]
### Describe the bug

Exception thrown Microsoft.UI.Xaml.Markup.XamlParseException: 'XAML parsing failed.' when adding <TextBox/> to XAML file. After removing <TextBox/> everything works flawlessly.

### Steps to reproduce the bug

1. Install .Net desktop development with Windows App SDK C# Templates
2. Install TemplateStudioForWinUICs
3. Create new project Template Studio for WinUI with self contained option
4. Deploy Project
5. Add TextBox between grid into MainPage.xaml deploy and start debugging.
6. Result Microsoft.UI.Xaml.Markup.XamlParseException: 'XAML parsing failed.'

Details

Microsoft.UI.Xaml.Markup.XamlParseException
  HResult=0x802B000A
  Message=XAML parsing failed.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.LoadComponent(IObjectReference _obj, Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at TextBoxBug.Views.MainPage.InitializeComponent() in C:\Users\User\source\repos\TextBoxBug\obj\x86\Debug\net6.0-windows10.0.19041.0\win10-x86\Views\MainPage.g.i.cs:line 39

### Expected behavior

No parsing error expected.

### Screenshots

![exception](https://user-images.githubusercontent.com/115322985/211059258-4291abb8-2365-4b7e-bf4a-e86f51d72aa4.PNG)
![MainPage xaml](https://user-images.githubusercontent.com/115322985/211059392-3911a38c-78b5-4764-b44e-9be7ff531cd3.png)

### NuGet package version

None

### Windows version

Windows 10 (21H2): Build 19044

**Comment by vsedge** [comment]
I was able to test code on Intel I5 processor and it worked my main machine on which this problem occurs has AMD Ryzen 5 1600AF. Same setup, same code just diffrent processor and it works.
