### ISSUE TITLE
COMException when using `StackPanel` as `FlipView.ItemsPanel` in a `StackPanel`

### ISSUE THREAD

**Issue by stephtr** [microsoft/microsoft-ui-xaml#8630]
### Describe the bug

When packing a `FlipView` into a `StackPanel` and setting `FlipView.ItemsPanel` to a `StackPanel` (see reproduction details below), the app crashes when the bound `ItemsSource` changes, in case both `StackPanel`'s orientation are the same.

The COMException states:
```
System.Runtime.InteropServices.COMException
  HResult=0x80004005
  Message = Error HRESULT E_FAIL has been returned from a call to a COM component.
  Source = WinRT.Runtime
  Call stack:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.System.Collections.Specialized.NotifyCollectionChangedEventHandler.NativeDelegateWrapper.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at App1.MainWindow.myButton_Click(Object sender, RoutedEventArgs e) in C:\Users\stroy\source\repos\App1\App1\MainWindow.xaml.cs:line 37
   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```

### Steps to reproduce the bug

Create a new WinUI 3 desktop app with:
```XAML
<StackPanel Orientation="Horizontal">
    <FlipView ItemsSource="{x:Bind VM.Items, Mode=OneWay}" x:Name="flip">
        <FlipView.ItemsPanel>
            <ItemsPanelTemplate>
                <StackPanel AreScrollSnapPointsRegular="False" Orientation="Horizontal"/>
            </ItemsPanelTemplate>
        </FlipView.ItemsPanel>
    </FlipView>
    <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
</StackPanel>
```
and
```C#
public sealed partial class MainWindow : Window
{
    public MainWindow()
    {
        this.InitializeComponent();
    }

    private ObservableCollection<string> Items = new();

    private void myButton_Click(object sender, RoutedEventArgs e)
    {
        Items.Add("Hello World");
    }
}
```
leads to the COM exception.

### NuGet package version

None

### Windows version

Windows Insider Build (xxxxx)

### Additional context

Windows 11 build 23486, .NET 7.0, WindowsAppSDK 1.3.230602002

**Comment by ranjeshj** [comment]
@stephtr What is the scenario you are trying to achieve ?

**Comment by stephtr** [comment]
The idea was to have a FlipView filled with controls, where the amount of controls depends on the bound items. The hope was that WinUI would then automatically figure out the optimal height for the FlipView.

<img width="386" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/5764184/2c16226a-96a2-415e-be1f-7c2f4102b3a9">

<img width="338" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/5764184/d124122b-af5f-4af0-8b19-ca254021218a">
