### ISSUE TITLE
clearing observable collection bound to ListView crashes with ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by busitech** [microsoft/microsoft-ui-xaml#8684]
## WinUI Toolkit Bug Report

---

**Name of components or parts of Toolkit:**
UIElement
ListViewRenderer.ListViewTransparent
ListViewRenderer
TemplatedItemsList
ListProxy
ObservableCollection

**Describe the bug:**
After calling ObservableCollection.Clear() the execution path travels down into the ABI and crashes there, in a virtual function table call to UpdateLayout, on an instance of ListViewRenderer.ListViewTransparent.  The event being processed is OnCollectionChanged, and the NotifyCollectionChangedEventArgsEx.Action is Reset.

**Version Info:**
SDK 7.0.306, RT 7.0.9, VS 17.6.33815.320, MAUI 7.0.92

**Additional context:**

System.ArgumentOutOfRangeException: This collection cannot work with indices larger than Int32.MaxValue - 1 (0x7FFFFFFF - 1). (Parameter 'index')
   at ABI.System.Collections.IList.ToAbiHelper.EnsureIndexInt32(UInt32 index, Int32 listCapacity)
   at ABI.System.Collections.IList.ToAbiHelper.GetAt(UInt32 index)
   at ABI.System.Collections.IList.Vftbl.Do_Abi_GetAt_0(IntPtr thisPtr, UInt32 index, IntPtr* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IUIElementMethods.UpdateLayout(IObjectReference _obj)
   at Microsoft.UI.Xaml.UIElement.UpdateLayout()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.<OnCollectionChanged>b__23_0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2.OnProxyCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.<>c__DisplayClass34_0.<OnCollectionChanged>b__0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.WeakNotifyProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at TestApp.TestAppUI.<UpdatePage>b__21_0()  <--- This calls ObservableCollection.Clear();
   at Microsoft.Maui.Dispatching.Dispatcher.<>c__DisplayClass9_0.<DispatchImplementation>b__0()
   at ABI.Microsoft.UI.Dispatching.DispatcherQueueHandler.Do_Abi_Invoke(IntPtr thisPtr)

**Comment by alphac05** [comment]
The same occurs when trying to simple remove an item like this:
```
public ObservableCollection<string> Items { get; set; } = new ObservableCollection<string>() { "One" };

private void Button_Clicked(object sender, EventArgs e)
{
    Items.RemoveAt(Items.Count - 1);
    Items.Add("new");
}
```

At the third click on the button, exception occurs.

**Comment by jsauve** [comment]
The same thing is happening for me on Android. The ObservableCollection works fine with ListView when items are added. As soon as a collection change action of `Reset` happens (because `Clear()` is called on the bound ObservableCollection), I see an ArgumentOutOfRangeException that appears to be bubbling up from the layout mechanism.

**Comment by ranjeshj** [comment]
Just tried on a simple WinUI3 app. ObservableCollection hooked to a ListView's itemssource seems to work as expected. Can you please share a WinUI 3 standalone example where this crash is happening?

**Comment by ranjeshj** [comment]
@yaira2 I tried with 100 items in itemssource. If you have a repro app, can you please share?

**Comment by busitech** [comment]
@ranjeshj  Here is your repro app.  Please reopen this issue.

[ObservableCollectionResetCrash.zip](https://github.com/microsoft/microsoft-ui-xaml/files/13593378/ObservableCollectionResetCrash.zip)

**Comment by busitech** [comment]
@ranjeshj You requested help with a repro app, and one was provided, yet the issue remains closed.  Please respond in some way to indicate how we can proceed.

**Comment by busitech** [comment]
@ranjeshj The crash is seen only on Windows, and I am reporting a Windows bug.  

Microsoft documentation states that "Windows apps built using .NET MAUI use Windows UI 3 (WinUI 3) library to create native apps that target the Windows desktop."

Therefore, please use the application project we shared to repro and resolve the issue.

**Comment by busitech** [comment]
@ranjeshj Are you going to reopen this case?

**Comment by bengavin** [comment]
We've also seeing this intermittently, but reliably, relevant portions of the stack trace are:

   at ABI.System.Collections.IList.ToAbiHelper.EnsureIndexInt32(UInt32 index, Int32 listCapacity)
   at ABI.System.Collections.IList.ToAbiHelper.GetAt(UInt32 index)
   at ABI.System.Collections.IList.Vftbl.Do_Abi_GetAt_0(IntPtr thisPtr, UInt32 index, IntPtr* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IUIElementMethods.UpdateLayout(IObjectReference _obj)
   at Microsoft.UI.Xaml.UIElement.UpdateLayout()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.<OnCollectionChanged>b__23_0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2.OnProxyCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.<>c__DisplayClass36_0.<OnCollectionChanged>b__0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.WeakNotifyCollectionChangedProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.Collection`1.Remove(T item)

**Comment by busitech** [comment]
@ranjeshj Please rejoin this discussion about a bug having the root cause in WinUI.  At your request we provided a way to reproduce.

**Comment by busitech** [comment]
@duncanmacmichael Would you please reopen this issue so we do not have to duplicate as a new issue?

**Comment by SKeehnen** [comment]
Any workaround for this? Just hit this issue as well.

**Comment by sjb-sjb** [comment]
I've found how to reproduce this bug (or a similar one). Can we get this fixed please.

1. Download the WinUI 3 Gallery and compile the WinUiGallery solution. 

2. In ControlPages / ListViewPage.xaml.cs, add "using Microsoft.UI.Xaml.Data;" at the top of the file and add the following collection class at the bottom of the namespace. This is an ObservableCollection implementing ISelectionInfo (not completely, but sufficiently for the demonstration). 

<code>
    public class ObservableCollectionSelector&lt;T&gt; : ObservableCollection&lt;T&gt;, ISelectionInfo
    {
        public ObservableCollectionSelector(IEnumerable&lt;T&gt; source) : base(source) { }
        private IList<ItemIndexRange> Selection = new List<ItemIndexRange>();

        public void SelectRange(ItemIndexRange itemIndexRange)
        {
            //Debug.WriteLine($"Select {itemIndexRange.FirstIndex}:{itemIndexRange.LastIndex}");
            if (this.Selection.Any(iir => iir.FirstIndex <= itemIndexRange.LastIndex + 1 && iir.LastIndex >= itemIndexRange.FirstIndex - 1)) { throw new NotSupportedException("failed select"); }
            this.Selection.Add(itemIndexRange);
        }
        public void DeselectRange(ItemIndexRange itemIndexRange)
        {
            //Debug.WriteLine($"Deselect {itemIndexRange.FirstIndex}:{itemIndexRange.LastIndex}");
            if (!this.Selection.Any(iir => iir.FirstIndex == itemIndexRange.FirstIndex && iir.LastIndex == itemIndexRange.LastIndex)) { throw new NotSupportedException("failed deselect"); }
            this.Selection.Remove(itemIndexRange);
        }
        public bool IsSelected(int index)
        {
            return this.Selection.Any(iir => iir.FirstIndex <= index && iir.LastIndex >= index);
        }
        public IReadOnlyList<ItemIndexRange> GetSelectedRanges()
        {
            //Debug.Assert(this.Selection.None((iir, i) => i > 0 && iir.FirstIndex <= this.Selection[i - 1].FirstIndex + 1));
            return this.Selection.AsReadOnly();
        }
    }
</code>

3. Around line 59, change <c>Control2.ItemsSource = await Contact.GetContactsAsync();</c> so that it is <c>Control2.ItemsSource = new ObservableCollectionSelector&lt;Contact&gt;( await Contact.GetContactsAsync());</c>

4. Run the app, select Collections on the left and then ListView. Scroll down to the second ListView ("ListView with Selection Support") and select Extended as the selection type. Click on the first entry ("Kendal Collins") and then CTRL-Click on the third entry ("Vance DeLeon"). Then release the control key and click on the 5th entry ("Amber Rodriguez"). 

5. Expected: the two selected items should be deselected and the new one should be selected. Actual: no change in visual state, and a crash with an ArgumentOutOfRange exception.

**Comment by sjb-sjb** [comment]
P.S. Noticing this issue is still closed, shouldn't it be re-opened?

**Comment by JochemPalmsens** [comment]
I'm also hitting this issue with the latest version of WinUI 3.
Something is going wrong when removing items from an ObservableCollection.

![Image](https://github.com/user-attachments/assets/d28540c2-cade-40e7-b45b-5c3b4580492f)

**Comment by sjb-sjb** [comment]
@JochemPalmsens  see #10025  for the suggestion that the selection may be invalidated when the collection changes, and a possible workaround.
