### ISSUE TITLE
Radiobutton: Error HRESULT E_FAIL has been returned from a call to a COM component.

### ISSUE THREAD

**Issue by Joost-Jens-Luminis** [microsoft/microsoft-ui-xaml#8698]
### Describe the bug

Occasionally, when loading a view with a radiobutton on it, and the radiobutton is selected we get the following error message:
Error HRESULT E_FAIL has been returned from a call to a COM component.

The stacktrace:
`   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.Primitives.IToggleButtonMethods.set_IsChecked(IObjectReference _obj, Nullable`1 value)
   at Bronkhorst.FlowControl.Windows.Views.Controls.RadioButtonWithInput.XamlBindingSetters.Set_Microsoft_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(ToggleButton obj, Nullable`1 value, String targetNullValue)
   at Bronkhorst.FlowControl.Windows.Views.Controls.RadioButtonWithInput.RadioButtonWithInput_obj1_Bindings.Update_IsChecked(Boolean obj, Int32 phase)
   at Bronkhorst.FlowControl.Windows.Views.Controls.RadioButtonWithInput.RadioButtonWithInput_obj1_Bindings.Update_(RadioButtonWithInput obj, Int32 phase)
   at Bronkhorst.FlowControl.Windows.Views.Controls.RadioButtonWithInput.RadioButtonWithInput_obj1_Bindings.Update()
   at Bronkhorst.FlowControl.Windows.Views.Controls.RadioButtonWithInput.RadioButtonWithInput_obj1_Bindings.Initialize()
   at Bronkhorst.FlowControl.Windows.Views.Controls.RadioButtonWithInput.RadioButtonWithInput_obj1_Bindings.Loading(FrameworkElement src, Object data)
   at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
`

The radiobutton is part of a component we created which called "RadioButtonWithInput". (Which is a RadioButton with an InputBox next to it inside a grid)
If I don't use our own component and only use the RadioButton, I stop getting the error, but after a few reloading of the view the selected RadioButton no longer has text standing next to it, and at that point selecting one of the other radiobuttons will give me the same error, but the StackTrace property is "null".

This is how we add the RadioButtons tot he View:
`                
<ItemsControl x:Name="ControlSensorItems" ItemsSource="{Binding ControlSettingItems}">
                    <ItemsControl.ItemTemplate>
                        <DataTemplate x:DataType="models:ControlFunctionSettingsListItem">
                            
                            <RadioButton
                                Grid.Column="0"
                                GroupName="ControlSensorItems"
                       
                                IsChecked="{Binding IsSelected, Mode=TwoWay}"
                                Content="{Binding Name}" />
                        </DataTemplate>
                    </ItemsControl.ItemTemplate>
                </ItemsControl>`

### Steps to reproduce the bug

1. Add a list of RadioButtons to the View
2. Have one of the RadioButtons as being selected
3. Repeatedly open and close the view
4. One of the above issue occurs usually within 10 attempts.

### Expected behavior

No exception

### NuGet package version

WinUI 3 - Windows App SDK 1.3.3: 1.3.230724000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by DmitriyKomin** [comment]
@Joost-Jens-Luminis , thank you for reporting this. Without a repro app, it is unlikely to be actionable for us. Can you help provide a repro app for this issue?

In addition, consider checking if there is a stowed exception that provides more information. More info on stowed exceptions here: [microsoft-ui-xaml/docs/debugging_crashes.md at main · microsoft/microsoft-ui-xaml (github.com)](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/debugging_crashes.md#stowed-exception-crashes-exception-code-0xc000027b)

**Comment by Joost-Jens-Luminis** [comment]
I will attempt to create a repro app this week.

**Comment by DmitriyKomin** [comment]
Reopening as we now have an internal repro for this.

**Comment by JJBrychell** [comment]
This issue has been addressed and is scheduled for the next preview release of 1.6.

Problem arises from managed garbage collection interaction with the internal radio button tables. When a radio button is named it is entered into an internal table that is searched when determining which button(s) to uncheck when a new button is checked. The entry stays in this table until the radio button is destructed, but with garbage collection it can stick around for a while after it been removed from the tree. So when you show/hide the view you can get multiple sets of radio buttons for the view in this internal table. This is handled correctly, except when the timing of garbage collection is just right. When garbage collection happens, it does so off the UI thread, so it only partially destructs the UI element and then schedules the rest of it to be done on the UI thread. If a check box checked changes comes in between when garbage collection has partially destructed the item, but the UI thread hasn't completed that destruction, the radio button code doesn't realize that even though it still exists, it is in a bad state that ultimately causes this crash. We have modified the process to no longer rely on any of the data that is partially destructed in garbage collection.

**Comment by rcg-wae** [comment]
If anyone is reading this after October 2024, the issue did also appear affect the toggle control. Updating to 1.6 also seems to have solved the problem there too.
