### ISSUE TITLE
Can't Send App notifications from Console app using Windows apps sdk

### ISSUE THREAD

**Issue by KWodarczyk** [microsoft/microsoft-ui-xaml#8777]
### Describe the bug

Can't Send App notifications from Console app using Windows apps sdk

Exception is thrown:

System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder..ctor()
   at Program.<Main>$(String[] args) in C:\Users\kwodarc\MyRepos\BugSandBox\ConsoleApp1\Program.cs:line 14

### Steps to reproduce the bug

Create Console app and use latest windows apps sdk pacage and copy paste the following code and run:

```
// See https://aka.ms/new-console-template for more information
using Microsoft.Windows.AppNotifications.Builder;
using Microsoft.Windows.AppNotifications;




Console.WriteLine("Send Toast ?");

Console.ReadLine();

try
{
    var appNotification = new AppNotificationBuilder()
                .AddArgument("action", "ToastClick")
                .AddText("Test Toast")
                .AddText("This is an example message")
                .BuildNotification();

    AppNotificationManager.Default.Show(appNotification);
}
catch (Exception ex)
{

	Console.WriteLine(ex.ToString());
}

Console.ReadLine();
```

### Expected behavior

toast sent

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/5243438/e838d87e-0e3d-4aeb-b206-22784ff9008c)

### NuGet package version

WinUI 3 - Windows App SDK 1.4 Preview 1: 1.4.230628000-preview1

### Windows version

Windows 11 (21H2): Build 22000

**Comment by kmgallahan** [comment]
Wrong repo: https://github.com/microsoft/WindowsAppSDK
