### ISSUE TITLE
[Regression] Failed to discovery tests for "UITests" with error "System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types" appeared

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/microsoft-ui-xaml#9400]
### Describe the bug

This is a regression issue, feature works well on 17.9, broken from 17.10.0 Preview 1.0 [34607.79.d17.10]

### Steps to reproduce the bug

1. Download the project from github [microsoft/WinUI-Samples: Official repository for WinUI sample code (github.com)](https://github.com/microsoft/WinUI-Samples)
2. Extract the project and launch solution "UITests.sln" 
(Note: need update the code for "bool isCausalitySupported()" in "xx:\WinUI-Samples-main\WinUI-Samples-main\Shared\WinUISplashScreen\Native\ppltasks.cpp" as feature change mentioned in https://github.com/microsoft/WinUI-Samples/issues/193
3. Wait for the solution load completely
4. Add Nuget source for "https://api.nuget.org/v3/index.json" and "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" under "Package Sources" tab for "Nuget Package Manager"
5. Restore NuGet package for solution
6. Build project "UITests"
7. Open Test->Test Explorer
8. Click "Run All Tests in View"

**Actual:**
Only 1 test for UnitTest was found and 1 Error appeared
![Fail](https://github.com/microsoft/microsoft-ui-xaml/assets/37648162/cfc44492-0289-44ec-bf3a-e0721e7b00ba)

Error info:
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.

   at EnvDTE.Property.get_Value()

   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectDataImpl.<GetRemoteMachineAddressAsync>d__36.MoveNext()

Starting test discovery for requested test run

========== Starting test discovery ==========

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)

   at System.Reflection.RuntimeModule.GetTypes()

   at System.Reflection.Assembly.GetTypes()

   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()

   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition)

   at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(ImportDefinition definition)

   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)

   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)

   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)

   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)

   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)

   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)

   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)

   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)

   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)

   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)

   at System.ComponentModel.Composition.Hosting.ImportEngine.TryGetExports(ExportProvider provider, ComposablePart part, ImportDefinition definition, AtomicComposition atomicComposition)

   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)

   at System.ComponentModel.Composition.Hosting.ImportEngine.TryPreviewImportsStateMachine(PartManager partManager, ComposablePart part, AtomicComposition atomicComposition)

   at System.ComponentModel.Composition.Hosting.ImportEngine.PreviewImports(ComposablePart part, AtomicComposition atomicComposition)

   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)

   at Microsoft.VisualStudio.UwpTestHostRuntimeProvider.Deployer..ctor(String target, String vsInstallPath, IMessageLogger messageLogger)

   at Microsoft.VisualStudio.UwpTestHostRuntimeProvider.UwpTestHostManager.get_Deployer()

   at Microsoft.VisualStudio.UwpTestHostRuntimeProvider.UwpTestHostManager.Microsoft.VisualStudio.TestPlatform.ObjectModel.Host.ITestRuntimeProvider.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyOperationManager.cs:line 223

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyDiscoveryManager.cs:line 149

========== Test discovery aborted: 0 Tests found in 22.5 ms ==========

========== Starting test run ==========

========== Test run finished: 1 Tests (1 Passed, 0 Failed, 0 Skipped) run in 58 ms ==========

### Expected behavior

6 Tests (1 for UnitTest and 5 for UITests) were found and all pass
![Works](https://github.com/microsoft/microsoft-ui-xaml/assets/37648162/6a921e39-9ae4-4dbf-a463-1a5c5a593936)

### NuGet package version

None

**Comment by PhoebeTf** [comment]
Tested with 17.10.0 Preview 2.0 [34707.107.d17.10], all tests can be discovered. Close it.
![Works_17 10Preview2](https://github.com/microsoft/microsoft-ui-xaml/assets/37648162/edccdda3-29f6-4f54-abfc-719152c9cf6e)
