### ISSUE TITLE
Proposal: Improve exception message for incorrect bound type using x:DataType

### ISSUE THREAD

**Issue by SoggyBottomBoy** [microsoft/microsoft-ui-xaml#9651]
# Proposal: Improve exception message for incorrect bound type using x:DataType

## Summary
When using controls relying on DataTemplate (i.e. ListView), if the items source does not match the data template type the exception thrown is vauge. The following exception is given:

> "System.ArgumentException: Source object type is not a projected type and does not inherit from a projected type. (Parameter 'value')
>    at WinRT.CastExtensions.GetRefForObject(Object value)
>    at WinRT.CastExtensions.As[TInterface](Object value)
>    at TestApp.Pages.Views.Page.Page_obj8_Bindings.SetDataRoot(Object newDataRoot)
>    at TestApp.Pages.Views.Page.Page_obj8_Bindings.ProcessBindings(Object item, Int32 itemIndex, Int32 phase, Int32& nextPhase)
>    at ABI.Microsoft.UI.Xaml.Markup.IDataTemplateComponent.Do_Abi_ProcessBindings_1(IntPtr thisPtr, IntPtr item, Int32 itemIndex, Int32 phase, Int32* nextPhase)"

The exception should provide some more context, like the type mismatch.

Ideally this would be checked at compile time. I am using x:Bind for the items source so potentially if the itemtemplate is set with a datatemplate with a known DataType it could be possible to validate this?

## Rationale
* Descriptive exceptions can help the developer better find runtime exception produced by Xaml

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to better understand xaml exceptions | Must |

**Comment by weitzhandler** [comment]
That's a nasty exception! I've been banging my head trying to figure where it's coming from, there's not even any stack trace as it's happening in the unmanaged part.
Thanks for you enlightening me, yes this is a very compelling issue.

**Comment by Wufus** [comment]
I often get this error when using DataTemplateSelector in all my projects. And it happens unpredictably: the same code can work, and can give an error
