### ISSUE TITLE
InvalidCastException in ItemsControl with custom container

### ISSUE THREAD

**Issue by hmg1000** [microsoft/microsoft-ui-xaml#9855]
### Describe the bug

Since version **1.6.240701003-experimental2** I'm getting an **InvalidCastException** in a custom ItemsControl when iterating over its container elements.

### Steps to reproduce the bug

```
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using System.Collections.Generic;
using System.Linq;

namespace TestWinUI;

internal class CustomItemsControl : ItemsControl
{
    public CustomItemsControl()
    {
        this.Loaded += TestControl_Loaded;
    }

    private void TestControl_Loaded(object sender, RoutedEventArgs e)
    {
        // Throws invalid cast exception:
        List<CustomItem> items = this.Items
            .Select((item, index) => this.ContainerFromIndex(index))
            .OfType<CustomItem>()
            .ToList();

        // This works:
        CustomItem customItem = (CustomItem)this.ContainerFromIndex(0);
    }

    protected override DependencyObject GetContainerForItemOverride()
    {
        return new CustomItem();
    }
}

internal class CustomItem : ContentControl
{
}
```

MainWindow.xaml:
```
<Window
    x:Class="TestWinUI.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:local="using:TestWinUI"
    mc:Ignorable="d">

    <local:CustomItemsControl x:Name="control"/>
</Window>
```

MainWindow.xaml.cs:
```
using Microsoft.UI.Xaml;

namespace TestWinUI;

public sealed partial class MainWindow : Window
{
    public MainWindow()
    {
        this.InitializeComponent();

        this.control.ItemsSource = new string[] { "1" };
    }
}
```

### Expected behavior

No InvalidCastException should be thrown

### NuGet package version

WinUI 3 - Windows App SDK 1.6 Experimental 2: 1.6.240701003-experimental2

### Additional context

This is the stacktrace of the InvalidCastException:

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.IObjectReference.As[T](Guid iid)
   at System.Collections.Generic.IEnumeratorImpl`1.Make_IEnumeratorObjRef()
   at System.Collections.Generic.IEnumeratorImpl`1.get_iEnumeratorObjRef()
   at System.Collections.Generic.IEnumeratorImpl`1.Windows.Foundation.Collections.IIterator<T>.get_HasCurrent()
   at ABI.System.Collections.Generic.FromAbiEnumerator`1.MoveNext()
   at System.Linq.Enumerable.<SelectIterator>d__229`2.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__66`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at TestWinUI.CustomItemsControl.TestControl_Loaded(Object sender, RoutedEventArgs e) in D:\Repos\TestWinUI\TestWinUI\CustomItemsControl.cs:line 18
   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)

**Comment by Scottj1s** [comment]
@hmg1000 Thanks for reporting this. A fix will be available in the next C#/WinRT release (thanks @manodasanW)

**Comment by hmg1000** [comment]
@Scottj1s This is still an issue in Windows App SDK 1.6 Preview 1. Will the fix be included in the final version?

**Comment by codendone** [comment]
@hmg1000 Have you tried adding a direct nuget package reference to [Microsoft.Windows.CsWinRT](https://www.nuget.org/packages/Microsoft.Windows.CsWinRT) 2.1.1? 1.6-preview1 references an older version. The final 1.6 will use 2.1.1 (or later).
