### ISSUE TITLE
Logic error in ItemsRepeater?

### ISSUE THREAD

**Issue by grokys** [microsoft/microsoft-ui-xaml#997]
**Describe the bug**

I'm currently porting `ItemsRepeater` to Avalonia (https://github.com/AvaloniaUI/Avalonia/pull/2603) and we were occasionally getting an `IndexOutOfRangeException`. I'm not 100% sure this is a problem in the WinUI code or if I've messed something up porting it to C#, but I thought I'd open this issue to check with you.

Stacktrace:

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
Arg_ParamName_Name
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Avalonia.Layout.ElementManager.GetLayoutBoundsForDataIndex(Int32 dataIndex) in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Layout\ElementManager.cs:line 175
   at Avalonia.Layout.FlowLayoutAlgorithm.RaiseLineArranged() in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Layout\FlowLayoutAlgorithm.cs:line 518
   at Avalonia.Layout.FlowLayoutAlgorithm.Measure(Size availableSize, VirtualizingLayoutContext context, Boolean isWrapping, Double minItemSpacing, Double lineSpacing, ScrollOrientation orientation, String layoutId) in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Layout\FlowLayoutAlgorithm.cs:line 107
   at Avalonia.Layout.UniformGridLayout.MeasureOverride(VirtualizingLayoutContext context, Size availableSize) in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Layout\UniformGridLayout.cs:line 403
   at Avalonia.Layout.VirtualizingLayout.Measure(LayoutContext context, Size availableSize) in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Layout\VirtualizingLayout.cs:line 37
   at Avalonia.Controls.ItemsRepeater.MeasureOverride(Size availableSize) in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Controls\Repeater\ItemsRepeater.cs:line 284
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 516
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 317
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 354
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Layout\LayoutManager.cs:line 196
   at Avalonia.Layout.LayoutManager.ExecuteArrangePass() in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Layout\LayoutManager.cs:line 147
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Layout\LayoutManager.cs:line 90
   at Avalonia.Controls.WindowBase.HandleResized(Size clientSize) in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Controls\WindowBase.cs:line 266
   at Avalonia.Controls.Window.HandleResized(Size clientSize) in D:\projects\AvaloniaUI\Avalonia\src\Avalonia.Controls\Window.cs:line 562
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in D:\projects\AvaloniaUI\Avalonia\src\Windows\Avalonia.Win32\WindowImpl.cs:line 700
   at Avalonia.Win32.Interop.UnmanagedMethods.DefWindowProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in D:\projects\AvaloniaUI\Avalonia\src\Windows\Avalonia.Win32\WindowImpl.cs:line 759
```

From my reading of the code, it's possible that this loop can be iterated 0 times if both conditions fail:

https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Repeater/FlowLayoutAlgorithm.cpp#L304-L305

In this case, `m_lastRealizedDataIndexInsideRealizationWindow` is updated expecting that the loop was iterated >= 1 time:

https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Repeater/FlowLayoutAlgorithm.cpp#L415-L418

This causes `m_lastRealizedDataIndexInsideRealizationWindow ` to be set to an incorrect value.

In Avalonia, I fixed the problem we were seeing by only updating the value if the loop was iterated: https://github.com/AvaloniaUI/Avalonia/pull/2603/commits/6f0befabdbf76fd97d936494fdf8f6e50cfe947e

I'm not 100% sure this is the correct fix, but it seems to have worked.

**Steps to reproduce the bug**

I've tried to reproduce the error in WinUI but I've been unable to so far.

**Version Info**

Current master: 7897ef32a4fd874d91a1e3be3d15a9186fffc068

**Comment by grokys** [comment]
Closing this as it looks like the problem was caused by a mistake in porting.
